// Copyright (c) 2010, Sybase Inc.


// Message/error strings used by clientrt and template-generated code

#define SUPCLIENTRT_EXECUTEQUERYEXCEPTIONMSG @"there is an exception in executeQuery: name: %@ reason:%@"
#define SUPCLIENTRT_MSGHEADERRECEIVED @"The message header received :"
#define SUPCLIENTRT_MSGCONTENTRECEIVED @"The message content received :"
#define SUPCLIENTRT_MSGHEADERSENDING @"The message header sending out :"
#define SUPCLIENTRT_MSGCONTENTSENDING @"The message content sending out:"
#define SUPCLIENTRT_CANNOTSYNCWITHINTIMEOUT @"can not synchronize with server within timeout"
#define SUPCLIENTRT_PERSISTENCEEXCEPTIONMSG @"SUPPersistenceException from %@: -- %@"
#define SUPCLIENTRT_MISSINGREQUIREDCONNPROFILEPROPERTY @"Missing required connection profile property: "
#define SUPCLIENTRT_LOADFROMKC_INVALIDPARAMETER @"invalid parameter"
#define SUPCLIENTRT_LOADFROMKC_GETPASSWITHUSERERROR @"getPassWithUser returns error: %@, %i"
#define SUPCLIENTRT_LOADFROMKC_GETKEYWITHUSERERROR @"getKeyWithUser returns error: %@, %i"
#define SUPCLIENTRT_SAVETOKC_STOREPASSWITHUSERERROR @"storePassWithUser returns error: %@, %i"
#define SUPCLIENTRT_SAVETOKC_STOREKEYWITHUSERERROR @"storeKeyWithUser returns error: %@, %i"
#define SUPCLIENTRT_MOCKDBMANAGERNOCONNECTION @"Cannot get a connection to a mock database"
#define SUPCLIENTRT_UNEXPECTEDNULL @"unexpected null value for \'"
#define SUPCLIENTRT_UNEXPECTEDTYPECODE @"unexpected typeCode: "
#define SUPCLIENTRT_UNDEFINEDALIAS @"undefined alias: "
#define SUPCLIENTRT_UNEXPECTEDOPERATOR @"unexpected operator: "
#define SUPCLIENTRT_UNEXPECTEDCRITERIA @"unexpected criteria: "
#define SUPCLIENTRT_JSONASSERTIONFAIL @"Assertion failed: (%s), method: %s"
#define SUPCLIENTRT_INVALIDPARAMETER @"%@: invalid parameter"
#define SUPCLIENTRT_KEYCHAIN_RETURNSERROR  @"%@ returns error: %i"
#define SUPCLIENTRT_KEYCHAIN_OVERRIDE1999 @"Override with -1999"
#define SUPCLIENTRT_LOCKUTIL_TIMEOUTMSG @"{thread:%p}: fail to get dblock within timeout"
#define SUPCLIENTRT_JSONREADER_UNEXPECTEDTOKENS @"unexpected tokens follow the parsed value"
#define SUPCLIENTRT_INVALIDJSONSTRING @"Invalid JSON string"
#define SUPCLIENTRT_JSON_EXPECTEDBRACKET @"expected \'{\' or \'[\', found \'"
#define SUPCLIENTRT_JSON_EXPECTEDCOMMA @"expected \',\', found \'"
#define SUPCLIENTRT_JSON_EXPECTEDCOLON @"expected \':\', found \'"
#define SUPCLIENTRT_JSON_MISSINGARRAYENDBRACKET @"missing \']\' at end of array"
#define SUPCLIENTRT_JSON_MISSINGOBJECTENDBRACKET @"missing \'}\' at end of array"
#define SUPCLIENTRT_JSON_UNTERMINATEDSTRING @"unterminated string"
#define SUPCLIENTRT_JSON_INVALIDBOOLEANVALUE_TRUE @"invalid value (expected true)"
#define SUPCLIENTRT_JSON_INVALIDBOOLEANVALUE_FALSE @"invalid value (expected false)"
#define SUPCLIENTRT_JSON_INVALIDVALUE_EXPECTEDNULL @"invalid value (expected null)"
#define SUPCLIENTRT_JSON_INVALIDVALUE_EXPECTEDNUMBER @"invalid value (expected number) starting with \'"
#define SUPCLIENTRT_JSON_INVALIDUNICODEESCAPE @"invalid unicode escape sequence"
#define SUPCLIENTRT_JSON_INVALIDSTRINGESCAPE @"invalid string escape character"
#define SUPCLIENTRT_JSON_INVALIDSTRINGCHARACTER @"invalid string character"
#define SUPCLIENTRT_JSON_INVALIDHEXADECIMAL @"invalid hexadecimal digit: "
#define SUPCLIENTRT_DB_EXCEPTION @"%@: There is an exception %@"
#define SUPCLIENTRT_DB_TRANSACTIONACTIVE @"Transaction already active"
#define SUPCLIENTRT_DB_RENAMEDBFAILED @"DB rename failed: "
#define SUPCLIENTRT_DB_ENCRYPT_PROFILEINVALID @"changeEncryptionKey: profile is invalid"
#define SUPCLIENTRT_DB_CANTUNENCRYPT @"fail to use unencrypt the db"
#define SUPCLIENTRT_DB_CANTUNENCRYPT_WITH_NEWKEY @"fail to use %@ unencrypting the db, %@"
#define SUPCLIENTRT_DB_DELETEDBFAILED @"DB delete failed: "
#define SUPCLIENTRT_DB_CANTENCRYPT @"fail to use encrypt the db"
#define SUPCLIENTRT_DB_CANTENCRYPT_WITH_NEWKEY @"fail to use %@ encrypting the db, %@"
#define SUPCLIENTRT_DB_UPDATE_ROWCHANGEDORDELETED @"update failed (row was changed or deleted by another transaction)"
#define SUPCLIENTRT_DB_DELETE_ROWCHANGEDORDELETED @"delete failed (row was changed or deleted by another transaction)"
#define SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG @"SUPPersistenceException from %@: -- %@"
#define SUPCLIENTRT_TEMPLATE_LOADRETURNEDNULLRESULT @"%@ returned null result"
#define SUPCLIENTRT_TEMPLATE_ILLEGALKEYGENERATORSTATUS @"Illegal key generator status. It must be populated first by the server after a client call to beginOnlineLogin or subscribe"
#define SUPCLIENTRT_MESSAGECLIENT_NOT_PROVISIONED @"- Required settings are not fully provisioned or contain invalid values, can not start."
#define SUPCLIENTRT_MESSAGECLIENT_KEYVAULT_NOT_AVAILABLE @"- Operation failed, Unable to access the key"
#define SUPCLIENTRT_MESSAGECLIENT_OPERATION_FAILURE @"- Operation failed"
#define SUPCLIENTRT_ABSTRACTCLASSEXCEPTION @"abstract class exception"
#define SUPCLIENTRT_NOSUCHATTRIBUTE @"no such attribute"
#define SUPCLIENTRT_NOSUCHPARAMETER @"no such parameter"
#define SUPCLIENTRT_NOSUCHOPERATION @"no such operation"
#define SUPCLIENTRT_NOSUCHCLASS @"no such class"
#define SUPCLIENTRT_WRONGDATATYPE @"wrong data type"
#define SUPCLIENTRT_INVALIDDATATYPE @"invalid data type"
#define SUPCLIENTRT_NULLDATAVALUE @"null data value"
#define SUPCLIENTRT_ONLINE_LOGIN_NO_CONNECTION_TO_SERVER @"No connection to server"
#define SUPCLIENTRT_ONLINE_LOGIN_SERVER_TIMED_OUT @"Server did not respond within timeout"
#define SUPCLIENTRT_SUBSCRIBEMISMATCH @"Package %@ not subscribed on server, but client thinks it was subscribed."
#define SUPCLIENTRT_PROTOCOLMISMATCH @"Device and server are not using compatible protocol versions: client protocol version = %d, server protocol version = %d." 
#define SUPCLIENTRT_PACKAGENOTSUBSCRIBED @"Package not subscribed"
