/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.0.1.314
*/ 

#import "RHM_Comercial_KeyPackageName.h"
#import "SUPJsonObject.h"

@implementation RHM_Comercial_KeyPackageName

@synthesize key_name = _key_name;
@synthesize package_name = _package_name;
@synthesize user_name = _user_name;
@synthesize domain_name = _domain_name;

- (id)initFromJson:(SUPJsonObject*)json:(int32_t)flags
{
    if (json == nil)
    {
        [self release];
        return nil;
    }
    if ((self = [super init]))
    {
        [self readJson:json:flags];
    }
    return self;   
}

- (void)readJson:(SUPJsonObject*)json:(int32_t)flags
{
    if ([json containsKey:@"key_name"])
    {
        self.key_name = [json getString:@"key_name"];
    }
    if ([json containsKey:@"package_name"])
    {
        self.package_name = [json getString:@"package_name"];
    }
    if ([json containsKey:@"user_name"])
    {
        self.user_name = [json getString:@"user_name"];
    }
    if ([json containsKey:@"domain_name"])
    {
        self.domain_name = [json getString:@"domain_name"];
    }
}

- (SUPJsonObject*)json:(int32_t)flags
{
    SUPJsonObject *newJson = [[SUPJsonObject alloc] init];
	[newJson setString:@"key_name":self.key_name];
	[newJson setString:@"package_name":self.package_name];
	[newJson setString:@"user_name":self.user_name];
	[newJson setString:@"domain_name":self.domain_name];
    [newJson autorelease];
    return newJson;
}
+ (SUPObjectList*)fromJSONList:(SUPJsonArray*)jsonArray
{
	if(jsonArray == nil)
		return nil;
	
	SUPObjectList* instanceList = [[SUPObjectList alloc] initWithCapacity:1];
	if(instanceList == nil)
		return nil;

	for (SUPJsonObject* jsonObject in jsonArray)
	{
	    RHM_Comercial_KeyPackageName* inst = [[RHM_Comercial_KeyPackageName alloc] initFromJson:jsonObject:0];
	    [instanceList add:inst];
	    [inst release];
	}
	return instanceList;
}

+ (SUPJsonArray*)toJSONList:(SUPObjectList*)instanceList
{
	SUPJsonArray* jsonArray = [[SUPJsonArray alloc] init];
	[jsonArray autorelease];
	for (RHM_Comercial_KeyPackageName* inst in instanceList)
	{
		[jsonArray add:[inst json:0]];
	}
	return jsonArray;
}
- (void)dealloc
{
    if(_key_name)
    {
        [_key_name release];
        _key_name = nil;
    }
    if(_package_name)
    {
        [_package_name release];
        _package_name = nil;
    }
    if(_user_name)
    {
        [_user_name release];
        _user_name = nil;
    }
    if(_domain_name)
    {
        [_domain_name release];
        _domain_name = nil;
    }
	[super dealloc];
}

static SUPClassMetaData* RHM_Comercial_KeyPackageName_META_DATA;
static BOOL _valid_ = NO;

+ (SUPClassMetaData*)metaData
{
    if (! (_valid_))
    {
 	   	RHM_Comercial_KeyPackageName_META_DATA = [[SUPEntityMetaData alloc] init];
 	   	SUPObjectList *attributes = [SUPObjectList listWithCapacity:7];
       	RHM_Comercial_KeyPackageName_META_DATA.name = @"KeyPackageName";
       	[RHM_Comercial_KeyPackageName_META_DATA setClass:[RHM_Comercial_KeyPackageName class]];
 
        	// Handle attributes
 		int attribute_counter = 0;
 
 		attribute_counter++;
		SUPAttributeMetaData_DC* a_key_name = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:attribute_counter:(SUPString)@"key_name":[SUPDataType forName:@"string"]];
  		[attributes addThis:a_key_name];
 
 		attribute_counter++;
		SUPAttributeMetaData_DC* a_package_name = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:attribute_counter:(SUPString)@"package_name":[SUPDataType forName:@"string"]];
  		[attributes addThis:a_package_name];
 
 		attribute_counter++;
		SUPAttributeMetaData_DC* a_user_name = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:attribute_counter:(SUPString)@"user_name":[SUPDataType forName:@"string"]];
  		[attributes addThis:a_user_name];
 
 		attribute_counter++;
		SUPAttributeMetaData_DC* a_domain_name = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:attribute_counter:(SUPString)@"domain_name":[SUPDataType forName:@"string"]];
  		[attributes addThis:a_domain_name];
 		RHM_Comercial_KeyPackageName_META_DATA.attributes = attributes;
 		
 		SUPAttributeMap * attributeMap = [SUPAttributeMap getInstance];
    	[attributeMap setAttributes:attributes];
    	RHM_Comercial_KeyPackageName_META_DATA.attributeMap = [attributeMap finishInit];
  
  		// Handle operations
 		int operation_counter = 0;	
 
  		SUPObjectList *operations = [SUPObjectList listWithCapacity:operation_counter];
 		RHM_Comercial_KeyPackageName_META_DATA.operations = operations;
 		
		SUPOperationMap *operationMap = [SUPOperationMap getInstance];
		[operationMap setOperations:operations];
		RHM_Comercial_KeyPackageName_META_DATA.operationMap = [operationMap finishInit];
	
     	_valid_ = YES;
	}
	return RHM_Comercial_KeyPackageName_META_DATA;
}

+ (RHM_Comercial_KeyPackageName*)getInstance
{
    RHM_Comercial_KeyPackageName* me = [[RHM_Comercial_KeyPackageName alloc] init];
    [me autorelease];
    return me;
}

@end