/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.0.1.314
*/ 

#import "RHM_Comercial_SubscriptionStatus.h"
#import "SUPJsonObject.h"
#import "SUPJsonArray.h"
#import "SUPJsonMessage.h"
#import "SUPJsonReader.h"
#import "SUPConnectionWrapper.h"
#import "SUPLocalTransaction.h"
#import "SUPObjectNotFoundException.h"
#import "SUPNoSuchOperationException.h"
#import "SUPQuery.h"
#import "SUPQueueConnection.h"
#import "SUPResultSetWrapper.h"
#import "SUPStatementWrapper.h"
#import "SUPStatementBuilder.h"
#import "SUPEntityMetaData.h"
#import "SUPOperationMetaData.h"
#import "SUPAttributeMetaData.h"
#import "SUPAttributeMetaData_DC.h"
#import "SUPDatabaseMetaData.h"
#import "SUPSelectItem.h"
#import "SUPAttributeMap.h"
#import "SUPOperationMap.h"
#import "SUPDataType.h"
#import "MBODebugLogger.h"
#import "RHM_Comercial_RHM_ComercialDB.h"
#import "RHM_Comercial_KeyGenerator.h"
#import "RHM_Comercial_LocalKeyGenerator.h"
#import "RHM_Comercial_KeyGeneratorPK.h"
#import "RHM_Comercial_LocalKeyGeneratorPK.h"
#import "RHM_Comercial_LogRecordImpl.h"
#import "SUPCallbackHandler.h"
#import "RHM_Comercial_Clientes.h"
#import "MBODebugSettings.h"

static NSObject<SUPCallbackHandler>* _callbackHandler = nil;

@interface RHM_Comercial_SubscriptionStatus(private)
- (void)bind:(id<SUPResultSetWrapper>)resultSet;
+ (RHM_Comercial_SubscriptionStatus*)find:(NSString*)id inTable:(SUPEntityTable)table;
+ (void)importData:(RHM_Comercial_SubscriptionStatus*)serverEntity:(SUPJsonObject*)jsonObject;
- (void)merge:(RHM_Comercial_SubscriptionStatus*)entity withJson:(SUPJsonObject*)json;
- (void)setAllAttributesFrom:(RHM_Comercial_SubscriptionStatus*)other;
@end
@implementation RHM_Comercial_SubscriptionStatus

@synthesize lastId = _lastId;
@synthesize status = _status;
@synthesize method = _method;

- (NSString*)method
{
    return _method;
}

- (void)setLastId:(NSString*)newLastId
{
    if (newLastId != self->_lastId)
    {
		[self->_lastId release];
        self->_lastId = [newLastId retain];
        self->_isDirty = YES;
    }
}

- (void)setStatus:(NSString*)newStatus
{
    if (newStatus != self->_status)
    {
		[self->_status release];
        self->_status = [newStatus retain];
        self->_isDirty = YES;
    }
}

- (void)setMethod:(NSString*)newMethod
{
    if (newMethod != self->_method)
    {
		[self->_method release];
        self->_method = [newMethod retain];
        self->_isNew = YES;
    }
}




- (id)initFromJson:(SUPJsonObject*)json:(int32_t)flags
{
    if (json == nil)
    {
        [self release];
        return nil;
    }
    if ((self = [super init]))
    {
        [self readJson:json:flags];
    }
    return self;   
}

- (void)readJson:(SUPJsonObject*)json:(int32_t)flags
{
        if ([json containsKey:@"lastId"])
    {
        self.lastId = [json getString:@"lastId"];
    }
        if ([json containsKey:@"status"])
    {
        self.status = [json getString:@"status"];
    }
        if ([json containsKey:@"method"])
    {
        self.method = [json getString:@"method"];
    }
    if ([json containsKey:@"_op"])
    {
    	unichar op = [json getChar:@"_op"];
    	self->_isNew = (op == PendingCreate);
    	self->_isDirty = (op == PendingUpdate);
    	self->_isDeleted = (op == PendingDelete);
    } else {
    	self->_isNew = YES;
    	self->_isDirty = NO;
    	self->_isDeleted = NO;
    }
}

- (SUPJsonObject*)json:(int32_t)flags
{
    SUPJsonObject *newJson = [[SUPJsonObject alloc] init];
	BOOL all = YES;
	if (self.isNew || self.isCreated)
	{
	    [newJson setChar:@"_op":PendingCreate];
	}
	else if (self.isDirty || self.isUpdated)
	{
	    [newJson setChar:@"_op":PendingUpdate];
	}
	else if ([self isDeleted])
	{
	    [newJson setChar:@"_op":PendingDelete];
	}
	else if ((flags & 2) == 2)
	{
	    [newJson setChar:@"_op":HasPendingChild];
		all = NO;
	}
	[newJson setString:@"method":self.method];
	if (all)
	{
	    [newJson setString:@"lastId":self.lastId];
	    [newJson setString:@"status":self.status];
	}
    [newJson autorelease];
    return newJson;
}
+ (SUPObjectList*)fromJSONList:(SUPJsonArray*)jsonArray
{
	if(jsonArray == nil)
		return nil;
	
	SUPObjectList* instanceList = [[SUPObjectList alloc] initWithCapacity:1];
	if(instanceList == nil)
		return nil;

	for (SUPJsonObject* jsonObject in jsonArray)
	{
	    RHM_Comercial_SubscriptionStatus* inst = [[RHM_Comercial_SubscriptionStatus alloc] initFromJson:jsonObject:0];
	    [instanceList add:inst];
	    [inst release];
	}
	return instanceList;
}

+ (SUPJsonArray*)toJSONList:(SUPObjectList*)instanceList
{
	SUPJsonArray* jsonArray = [[SUPJsonArray alloc] init];
	[jsonArray autorelease];
	for (RHM_Comercial_SubscriptionStatus* inst in instanceList)
	{
		[jsonArray add:[inst json:0]];
	}
	return jsonArray;
}
- (void)dealloc
{
    if(_lastId)
    {
        [_lastId release];
        _lastId = nil;
    }
    if(_status)
    {
        [_status release];
        _status = nil;
    }
    if(_method)
    {
        [_method release];
        _method = nil;
    }
	[super dealloc];
}

- (void)bind:(id<SUPResultSetWrapper>)resultSet
{
    @try
    {
        self.lastId = [resultSet getString:1:@"a"];
        self.status = [resultSet getString:2:@"c"];
        self.method = [resultSet getString:3:@"b"];
                        [self setOriginalState:nil];
        self->_originalStateValid = NO;
                                                self->_isNew = NO;
        self->_isDirty = NO;
        self->_isDeleted = NO;
    }
    @catch (SUPPersistenceException *spe)
    {
        MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"bind",[spe message]);
    }
}

- (void)clearRelationshipObjects
{
}

- (void)copyAll:(RHM_Comercial_SubscriptionStatus*)other
{
	[self copyAll:other withParent:(SUPAbstractEntity*)other];
}


- (void)copyAll:(RHM_Comercial_SubscriptionStatus*)other withParent:(SUPAbstractEntity*)parent
{
    [self setLastId:other.lastId];
    
    [self setStatus:other.status];
    
    [self setMethod:other.method];
    
	self->_isNew = other->_isNew;

}

- (void)create
{
	[super create];
}

- (void)delete
{
	[super delete];
}

- (RHM_Comercial_RHM_ComercialDB*)database
{
   return [RHM_Comercial_RHM_ComercialDB instance];
}

+ (RHM_Comercial_SubscriptionStatus*)find_by_id_string:(NSString*)id_string
{
    if(id_string == nil) return nil;
	NSString* key;
    key = id_string;
    return [RHM_Comercial_SubscriptionStatus find:key];
	
}

+ (RHM_Comercial_SubscriptionStatus*)find:(NSString*)id
{
	return [self find:id inTable:MainEntityTable];
}

+ (RHM_Comercial_SubscriptionStatus*)find:(NSString*)id_ inTable:(SUPEntityTable)table
{
    RHM_Comercial_SubscriptionStatus* result = nil;
	RHM_Comercial_SubscriptionStatus* downloadState = nil;
    id<SUPStatementWrapper> preparedStatement = nil;
    id<SUPConnectionWrapper> connection = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
    
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
    	//@synchronized(connection)
    	{
        	@try
        	{
            	if (table == MainEntityTable)
            	{
                	preparedStatement = [connection prepareStatement:@"select \"a\",\"c\",\"b\" from rhm_comercial_1_0_subscriptionstatus where \"b\"=?"];
            	}
            	else
            	{
                	preparedStatement = [connection prepareStatement:@"select \"a\",\"c\",\"b\" from rhm_comercial_1_0_subscriptionstatus_os where \"b\"=?"];
            	}
            	[preparedStatement setString:1:@"method":id_];
            	id<SUPResultSetWrapper> resultSet = [preparedStatement executeQuery];
            	while ([resultSet next])
            	{
            		if(result) [result release];
                	result = [[RHM_Comercial_SubscriptionStatus alloc] init];
                	[result bind:resultSet];
                	if (table == OriginalStateEntityTable)
                	{
                    	result->_pending = false;
                    	result->_pendingChange = NotPending;
                	}
                	if (result.pending)
                	{
                    	break;
                	}
                	else
                	{
 	              		downloadState = [RHM_Comercial_SubscriptionStatus getInstance];
                		[downloadState copyAll:result];
                	}
            	}
            	[resultSet close];      
        	}
        	@catch (SUPPersistenceException *spe)
        	{
            	@throw spe;
        	}
    	}
    }
    @catch (SUPPersistenceException *spe)
    {
        MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"find",[spe message]);
    }
    @finally
    {
    	if(preparedStatement) [preparedStatement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }
    if(result)
    {
    	if(result.pending)
    		result.downloadState = (SUPAbstractEntity*)downloadState;
  		//if(result != downloadState)
  		//	[downloadState release];
    }
    [result autorelease];
    return result;
}

+ (id<SUPSynchronizationGroup>)getSynchronizationGroup
{
	return [RHM_Comercial_RHM_ComercialDB getSyncGroupForName:@""];
}


- (id<SUPStatementWrapper>)getCreateStatement:(id<SUPConnectionWrapper>)connection forTable:(SUPEntityTable)table;
{
    id<SUPStatementWrapper> preparedStatement;
    preparedStatement = [connection prepareStatement:@"insert into rhm_comercial_1_0_subscriptionstatus (\"a\",\"c\",\"b\") values (?,?,?)"];
    // Add updated values
	if(self.lastId == nil)
		self.lastId = @"";
		//RHM_Comercial_SubscriptionStatus getCreateStatement:lastId not allowed to be null
    [preparedStatement setString:1:@"a":self.lastId];
	if(self.status == nil)
		self.status = @"";
		//RHM_Comercial_SubscriptionStatus getCreateStatement:status not allowed to be null
    [preparedStatement setString:2:@"c":self.status];
	if(self.method == nil)
		self.method = @"";
		//RHM_Comercial_SubscriptionStatus getCreateStatement:method not allowed to be null
    [preparedStatement setString:3:@"b":self.method];
	return preparedStatement;
}

- (id<SUPStatementWrapper>)getDeleteStatement:(id<SUPConnectionWrapper>)connection forTable:(SUPEntityTable)table;
{
    id<SUPStatementWrapper> preparedStatement;
    preparedStatement = [connection prepareStatement:@"delete from rhm_comercial_1_0_subscriptionstatus where \"b\"=?"];
    // Fill in values for "where" clause
    [preparedStatement setString:1:@"b":self.method];
	return preparedStatement;
}

- (id<SUPStatementWrapper>)getUpdateStatement:(id<SUPConnectionWrapper>)connection forTable:(SUPEntityTable)table;
{
    id<SUPStatementWrapper> preparedStatement;
	preparedStatement = [connection prepareStatement:@"update rhm_comercial_1_0_subscriptionstatus set \"a\"=?,\"c\"=? where \"b\"=?"];
    // Add updated values
    int parameterIndex = 0;
	if(self.lastId == nil)
		self.lastId = @"";
		//RHM_Comercial_SubscriptionStatus getUpdateStatement:lastId not allowed to be null
    parameterIndex++;
    [preparedStatement setString:parameterIndex:@"a":self.lastId];
	if(self.status == nil)
		self.status = @"";
		//RHM_Comercial_SubscriptionStatus getUpdateStatement:status not allowed to be null
    parameterIndex++;
    [preparedStatement setString:parameterIndex:@"c":self.status];
    // Fill in values for "where" clause
    parameterIndex++;
    [preparedStatement setString:parameterIndex:@"b":self.method];
	return preparedStatement;
}

- (NSString*)_pk
{
	return [self id];
}

- (NSString*)id
{
    return self.method;
}

- (NSString*)keyToString
{
	return [[self id] description];
}



+ (RHM_Comercial_SubscriptionStatus*)load:(NSString*)id
{
	RHM_Comercial_SubscriptionStatus* entity = [self find:id inTable:MainEntityTable];
	//RHM_Comercial_SubscriptionStatus* entity = [self find:id];
    if (entity == nil)
    {
		@throw [SUPObjectNotFoundException withMessage:@"-load: in RHM_Comercial_SubscriptionStatus: entity not found in database"];
    }
    return entity;
}

static SUPEntityMetaData* RHM_Comercial_SubscriptionStatus_META_DATA;
static BOOL _valid_ = NO;

+ (SUPEntityMetaData*)metaData
{
    if (! (_valid_))
    {
       RHM_Comercial_SubscriptionStatus_META_DATA = [SUPEntityMetaData getInstance];
       RHM_Comercial_SubscriptionStatus_META_DATA.id = _ENTITY_NUMBER_FOR_RHM_Comercial_SubscriptionStatus_;
       RHM_Comercial_SubscriptionStatus_META_DATA.name = @"SubscriptionStatus";
       [RHM_Comercial_SubscriptionStatus_META_DATA setClass:[RHM_Comercial_SubscriptionStatus class]];

	   RHM_Comercial_SubscriptionStatus_META_DATA.isClientOnly = YES;

       // Handle attributes
       
       	SUPObjectList *attributes = [SUPObjectList getInstance];
		SUPAttributeMetaData_DC* a_lastId = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:1:(SUPString)@"lastId":[SUPDataType forName:@"string"]];
		[a_lastId setColumn:@"\"a\""];
		[a_lastId setMaxLength:300];
		[a_lastId setPrecision:0];
		[a_lastId setScale:0];
		[a_lastId setIsKey:NO];
		SUPAttributeMetaData_DC* a_status = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:2:(SUPString)@"status":[SUPDataType forName:@"string"]];
		[a_status setColumn:@"\"c\""];
		[a_status setMaxLength:300];
		[a_status setPrecision:0];
		[a_status setScale:0];
		[a_status setIsKey:NO];
		SUPAttributeMetaData_DC* a_method = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:3:(SUPString)@"method":[SUPDataType forName:@"string"]];
		[a_method setColumn:@"\"b\""];
		[a_method setMaxLength:300];
		[a_method setPrecision:0];
		[a_method setScale:0];
		[a_method setIsKey:YES];
 		
 		[attributes addThis:a_lastId];
 		[attributes addThis:a_status];
 		[attributes addThis:a_method];
 		RHM_Comercial_SubscriptionStatus_META_DATA.attributes = attributes;
 		
 		SUPAttributeMap * attributeMap = [SUPAttributeMap getInstance];
    	[attributeMap setAttributes:attributes];
    	RHM_Comercial_SubscriptionStatus_META_DATA.attributeMap = [attributeMap finishInit];
 
 		// Handle operations
 		SUPOperationMetaData* o_store_3 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:1:(SUPString)@"store":[SUPDataType forName:@"void"]:true];
  		{
 			SUPObjectList *parameters_list = nil;
 			SUPParameterMetaData* p_store_id = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:1:(SUPString)@"id":[SUPDataType forName:@"string"]];
 			SUPParameterMetaData* p_store_method = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:2:(SUPString)@"method":[SUPDataType forName:@"string"]];
 			SUPParameterMetaData* p_store_status = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:3:(SUPString)@"status":[SUPDataType forName:@"string"]];
 			parameters_list = [SUPObjectList listWithCapacity:3];
 			[parameters_list addThis:p_store_id];
 			[parameters_list addThis:p_store_method];
 			[parameters_list addThis:p_store_status];
 			o_store_3.parameters = parameters_list;

 		}
		[o_store_3 setIsStatic:YES];
		[o_store_3 setIsCreate:NO];
		[o_store_3 setIsUpdate:NO];
		[o_store_3 setIsDelete:NO]; 		
 		[o_store_3 finishInit];
 		SUPOperationMetaData* o_onMessage_1 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:2:(SUPString)@"onMessage":[SUPDataType forName:@"void"]:true];
  		{
 			SUPObjectList *parameters_list = nil;
 			SUPParameterMetaData* p_onMessage_message = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:1:(SUPString)@"message":[SUPDataType forName:@"com.sybase.afx.json.JsonMessage"]];
 			parameters_list = [SUPObjectList listWithCapacity:1];
 			[parameters_list addThis:p_onMessage_message];
 			o_onMessage_1.parameters = parameters_list;

 		}
		[o_onMessage_1 setIsStatic:YES];
		[o_onMessage_1 setIsCreate:NO];
		[o_onMessage_1 setIsUpdate:NO];
		[o_onMessage_1 setIsDelete:NO]; 		
 		[o_onMessage_1 finishInit];
 		SUPOperationMetaData* o_findPending_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:3:(SUPString)@"findPending":[SUPDataType forName:@"SubscriptionStatus*"]:true];
		[o_findPending_0 setIsStatic:YES];
		[o_findPending_0 setIsCreate:NO];
		[o_findPending_0 setIsUpdate:NO];
		[o_findPending_0 setIsDelete:NO]; 		
 		[o_findPending_0 finishInit];
 		SUPOperationMetaData* o_refresh_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:4:(SUPString)@"refresh":[SUPDataType forName:@"void"]:true];
		[o_refresh_0 setIsStatic:NO];
		[o_refresh_0 setIsCreate:NO];
		[o_refresh_0 setIsUpdate:NO];
		[o_refresh_0 setIsDelete:NO]; 		
 		[o_refresh_0 finishInit];
 		SUPOperationMetaData* o__pk_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:5:(SUPString)@"_pk":[SUPDataType forName:@"string?"]:true];
		[o__pk_0 setIsStatic:NO];
		[o__pk_0 setIsCreate:NO];
		[o__pk_0 setIsUpdate:NO];
		[o__pk_0 setIsDelete:NO]; 		
 		[o__pk_0 finishInit];
 		SUPOperationMetaData* o_save_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:6:(SUPString)@"save":[SUPDataType forName:@"void"]:true];
		[o_save_0 setIsStatic:NO];
		[o_save_0 setIsCreate:NO];
		[o_save_0 setIsUpdate:NO];
		[o_save_0 setIsDelete:NO]; 		
 		[o_save_0 finishInit];
 
  		SUPObjectList *operations = [SUPObjectList listWithCapacity:6];
 		[operations addThis:o_store_3];
 		[operations addThis:o_onMessage_1];
 		[operations addThis:o_findPending_0];
 		[operations addThis:o_refresh_0];
 		[operations addThis:o__pk_0];
 		[operations addThis:o_save_0];
 		RHM_Comercial_SubscriptionStatus_META_DATA.operations = operations;
 		
		SUPOperationMap *operationMap = [SUPOperationMap getInstance];
		[operationMap setOperations:operations];
		RHM_Comercial_SubscriptionStatus_META_DATA.operationMap = [operationMap finishInit];
		
		RHM_Comercial_SubscriptionStatus_META_DATA.table = @"\"rhm_comercial_1_0_subscriptionstatus\"";

 		[RHM_Comercial_SubscriptionStatus_META_DATA retain];
     	_valid_ = YES;

	}
	return RHM_Comercial_SubscriptionStatus_META_DATA;
}

- (void)merge:(RHM_Comercial_SubscriptionStatus*)entity withJson:(SUPJsonObject*)json
{
	[super merge:entity withJson:json];
    if(![json containsKey:@"lastId"] )
    {
    	self.lastId = entity.lastId;
    }
    else if(![json getString:@"lastId"])
    {
    	self.lastId = entity.lastId;
    }
    if(![json containsKey:@"status"] )
    {
    	self.status = entity.status;
    }
    else if(![json getString:@"status"])
    {
    	self.status = entity.status;
    }
    if(![json containsKey:@"method"] )
    {
    	self.method = entity.method;
    }
    else if(![json getString:@"method"])
    {
    	self.method = entity.method;
    }
}

+ (RHM_Comercial_SubscriptionStatus*)getInstance
{
    RHM_Comercial_SubscriptionStatus* me = [[RHM_Comercial_SubscriptionStatus alloc] init];
    [me autorelease];
    return me;
}

- (SUPObjectList*)getLogRecords
{
    SUPQuery *query = [SUPQuery getInstance];
    [query from:@"LogRecordImpl":@"a"];
    query.testCriteria = (SUPTestCriteria*)[[SUPAttributeTest match:@"component":@"SubscriptionStatus"] and:[SUPAttributeTest match:@"entityKey":[self keyToString]]];
    [query orderBy:@"requestId":[SUPSortOrder DESCENDING]];

    RHM_Comercial_LogRecordImplList* list = [RHM_Comercial_LogRecordImpl findWithQuery:query];
    return (SUPObjectList*)list;
}

- (id<SUPLogRecord>)createLogRecord:(int32_t)level withMessage:(NSString*)message
{
    {
        RHM_Comercial_LogRecordImpl *log = [[RHM_Comercial_LogRecordImpl alloc] init];
        //log.level = [NSString stringWithFormat:@"%ld",[SUPLogLevel fromString:level]];
        log.level = level;
        log.message = message;
        log.messageId = [RHM_Comercial_KeyGenerator generateId];
        log.requestId = [NSString stringWithFormat:@"%ld",log.messageId];
        NSDate *timestamp = [NSDate dateWithTimeIntervalSinceNow:0];
        log.timestamp = timestamp;
        log.code = CLIENT_ENTITY_CREATED_LOGRECORD_CODE;
        log.component = @"SubscriptionStatus";
        log.entityKey = [self keyToString];
        [log save];
        [log autorelease];
        return log;
    }
}

- (void)setAllAttributesFrom:(RHM_Comercial_SubscriptionStatus*)other
{
	// Child lists are set to nil, to prevent infinite recursion
	// when this method is used inside the bind: method
    	[self setLastId:other.lastId];
    	[self setStatus:other.status];
    	[self setMethod:other.method];
}

+ (NSObject<SUPCallbackHandler>*)callbackHandler
{
	return _callbackHandler;
}

+ (void)registerCallbackHandler:(NSObject<SUPCallbackHandler>*)newCallbackHandler
{
	if(newCallbackHandler != _callbackHandler)
	{
		[_callbackHandler release];
		_callbackHandler = [newCallbackHandler retain];
	}
}

- (void)refresh
{
    if (!self.isNew)
    {
        RHM_Comercial_SubscriptionStatus* entity = [RHM_Comercial_SubscriptionStatus load:[self id]];
        [self copyAll:entity];
        _isNew = NO;
        _isDirty = NO;
    }
}











- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	SubscriptionStatus = \n\
	    lastId = %@,\n\
	    status = %@,\n\
	    method = %@,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.lastId
    	,self.status
    	,self.method
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}

- (void)save
{
    if (self->_isNew)
    {
        [self create];
    }
    else if (self->_isDirty)
    {
        [self update];
    }
}

- (void)createOrUpdateClientOnly
{
   	id<SUPConnectionWrapper> connection = nil;
    id<SUPStatementWrapper> statement = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
        RHM_Comercial_SubscriptionStatus *ms = [RHM_Comercial_SubscriptionStatus find:[self id] inTable:MainEntityTable];
		if(ms)
		{
			statement = [self getUpdateStatement:connection forTable:MainEntityTable];
			[statement executeUpdate:YES];
		} else {
		    statement = [self getCreateStatement:connection forTable:MainEntityTable];
			[statement executeInsert];
		}
			
		self->_isNew = NO;
		self->_isDirty = NO;
		self->_isDeleted = NO;
	}
	@catch (SUPPersistenceException *spe)
    {
        MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"createPending",[spe message]);
    }
    @finally
    {
        [statement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }    
}

- (void)createPending:(BOOL)isPending
{
	[self createOrUpdateClientOnly];
}

- (void)updatePending:(BOOL)isPending
{
	[self createOrUpdateClientOnly];
}




- (SUPAbstractEntity*)topLevelParent
{
	return self;
}

- (void)update
{
	[super update];
}


/*!
  @method
  @abstract Generated class method 
  @param id_
  @param method
  @param status
  @throws SUPPersistenceException
 */
+ (void)store:(NSString*)id_ withMethod:(NSString*)method withStatus:(NSString*)status
{
    BOOL newRec = NO;
    RHM_Comercial_SubscriptionStatus* subStatus = [RHM_Comercial_SubscriptionStatus find:method];
    if (subStatus == nil) {
        subStatus = [[RHM_Comercial_SubscriptionStatus alloc] init];
        [subStatus autorelease];
        newRec = YES;
    }
    subStatus.lastId = id_;
    subStatus.method = method;
    subStatus.status = status;
    if (newRec)
    {
    	[subStatus createPending:NO];
    } else {
    	[subStatus updatePending:NO];
    }
}

/*!
  @method
  @abstract Generated class method 
  @param message
  @throws SUPPersistenceException
 */
+ (void)onMessage:(SUPJsonMessage*)message
{
    SUPJsonObject* headers = message.headers;
    if(headers == nil)
    {
    	MBOLogError(@"SubscriptionStatus onMessage: nil header");
    	return;
    }
    SUPNullableString requestId = [headers getNullableString:@"id"];
    SUPNullableString method = [headers getNullableString:@"method"];
    SUPString status = @"unknown";
    BOOL success = NO;
    SUPInt cid;
    SUPString methodToReset;
    
    // check for import and server to client methods with no request ID
    if (requestId == nil) {
        return;
    }
        
    if ([method hasSuffix:@"Result"]) {
        status = @"success";
        success = YES;
    }
    else if ([method hasSuffix:@"Failed"]) {
        status = @"failed";
    }
    method = [method substringToIndex:[method length] - 6];
            
    RHM_Comercial_SubscriptionStatus* s = [RHM_Comercial_SubscriptionStatus find:method];
    if (s != nil && [requestId isEqualToString:s.lastId]) {
        s.status = status;
        [s updatePending:NO];
        
        if (success) {
            methodToReset = nil;
            // Reverse status of opposite methods
            if ([method hasPrefix:@"suspend"]) {
                methodToReset = @"resume";
            }
            else if ([method hasPrefix:@"resume"]) {
                methodToReset = @"suspend";
            }
             else if ([method hasPrefix:@"subscribe"]) {
                methodToReset = @"unsubscribe";
                // save the CID in the request ID field
                cid = [headers getInt:@"cid"];
                s.lastId = [NSString stringWithFormat:@"%d", cid];;
                [s updatePending:NO];
            }
            else if ([method hasPrefix:@"unsubscribe"]) {
                methodToReset = @"subscribe";
                // save the CID in the request ID field
                cid = [headers getInt:@"cid"];
                s.lastId = [NSString stringWithFormat:@"%d", cid];;
                [s updatePending:NO];
            }
            if (methodToReset != nil) {
                s = [RHM_Comercial_SubscriptionStatus find:methodToReset];
                if (s != nil) {
                    s.status = @"unknown";
                    s.lastId = @"0";
                    [s updatePending:NO];
                }
            }
        }
    }
}



+ (SUPObjectList*)findPending
{
	return [self findPending:0 take:-1]; 
}


	

+ (SUPObjectList*)findPending:(int32_t)skip take:(int32_t)take
{
	SUPObjectList* result = [[[SUPObjectList alloc] init] autorelease];
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:108];
	    [sql appendString:@"select x.\"a\",x.\"c\",x.\"b\" from \"rhm_comercial_1_0_subscriptionstatus\" x where x.\"c\" = \'pending\'"];
	    if(take != -1)
	        [sql appendFormat:@" limit %i",take];
	    if(skip != 0)
	        [sql appendFormat:@" offset %i",skip];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        RHM_Comercial_SubscriptionStatus* entity = [[RHM_Comercial_SubscriptionStatus alloc] init];
	        [entity bind:resultSet];
	        [result add:entity];
			[entity release];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"findPending",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}

@end