/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.0.1.314
*/ 

#import "RHM_Comercial_Clientes_pull_pq.h"
#import "SUPJsonObject.h"
#import "SUPJsonArray.h"
#import "SUPJsonMessage.h"
#import "SUPJsonReader.h"
#import "SUPConnectionWrapper.h"
#import "SUPLocalTransaction.h"
#import "SUPObjectNotFoundException.h"
#import "SUPNoSuchOperationException.h"
#import "SUPQuery.h"
#import "SUPQueueConnection.h"
#import "SUPResultSetWrapper.h"
#import "SUPStatementWrapper.h"
#import "SUPStatementBuilder.h"
#import "SUPEntityMetaData.h"
#import "SUPOperationMetaData.h"
#import "SUPAttributeMetaData.h"
#import "SUPAttributeMetaData_DC.h"
#import "SUPDatabaseMetaData.h"
#import "SUPSelectItem.h"
#import "SUPAttributeMap.h"
#import "SUPOperationMap.h"
#import "SUPDataType.h"
#import "MBODebugLogger.h"
#import "RHM_Comercial_RHM_ComercialDB.h"
#import "RHM_Comercial_KeyGenerator.h"
#import "RHM_Comercial_LocalKeyGenerator.h"
#import "RHM_Comercial_KeyGeneratorPK.h"
#import "RHM_Comercial_LocalKeyGeneratorPK.h"
#import "RHM_Comercial_LogRecordImpl.h"
#import "SUPCallbackHandler.h"
#import "RHM_Comercial_Clientes.h"
#import "MBODebugSettings.h"

static NSObject<SUPCallbackHandler>* _callbackHandler = nil;

@interface RHM_Comercial_Clientes_pull_pq(private)
- (void)bind:(id<SUPResultSetWrapper>)resultSet;
+ (RHM_Comercial_Clientes_pull_pq*)find:(int64_t)id inTable:(SUPEntityTable)table;
+ (void)importData:(RHM_Comercial_Clientes_pull_pq*)serverEntity:(SUPJsonObject*)jsonObject;
- (void)merge:(RHM_Comercial_Clientes_pull_pq*)entity withJson:(SUPJsonObject*)json;
- (void)setAllAttributesFrom:(RHM_Comercial_Clientes_pull_pq*)other;
@end
@implementation RHM_Comercial_Clientes_pull_pq

@synthesize username = _username;
@synthesize remoteId = _remoteId;
@synthesize agenteParam = _agenteParam;
@synthesize id_ = _id;

- (int64_t)id_
{
    if (_id == 0)
        _id = (int64_t)[RHM_Comercial_KeyGenerator generateId];
    return _id;
}

- (void)setUsername:(NSString*)newUsername
{
    if (newUsername != self->_username)
    {
		[self->_username release];
        self->_username = [newUsername retain];
        self->_isDirty = YES;
    }
}

- (void)setRemoteId:(NSString*)newRemoteId
{
    if (newRemoteId != self->_remoteId)
    {
		[self->_remoteId release];
        self->_remoteId = [newRemoteId retain];
        self->_isDirty = YES;
    }
}

- (void)setAgenteParam:(NSString*)newAgenteParam
{
    if (newAgenteParam != self->_agenteParam)
    {
		[self->_agenteParam release];
        self->_agenteParam = [newAgenteParam retain];
        self->_isDirty = YES;
    }
}

- (void)setId_:(int64_t)newId_
{
    if (newId_ != self->_id)
    {
        self->_id = newId_;
        self->_isNew = YES;
    }
}


- (SUPLong)replayCounter
{
    if ((_replayCounter == 0))
    {  
        _replayCounter = ((SUPLong)([RHM_Comercial_LocalKeyGenerator generateId]));
    }
    return _replayCounter;
}

- (void)setReplayCounter:(SUPLong)newReplayCounter
{
    if (! ((_replayCounter == newReplayCounter)))
    {  
        self->_isDirty = YES;
        _replayCounter = newReplayCounter;
    }
}

- (id)initFromJson:(SUPJsonObject*)json:(int32_t)flags
{
    if (json == nil)
    {
        [self release];
        return nil;
    }
    if ((self = [super init]))
    {
        [self readJson:json:flags];
    }
    return self;   
}

- (void)readJson:(SUPJsonObject*)json:(int32_t)flags
{
        if ([json containsKey:@"username"])
    {
        self.username = [json getNullableString:@"username"];
    }
        if ([json containsKey:@"remoteId"])
    {
        self.remoteId = [json getNullableString:@"remoteId"];
    }
        if ([json containsKey:@"agenteParam"])
    {
        self.agenteParam = [json getNullableString:@"agenteParam"];
    }
                        if ([json containsKey:@"id"])
    {
        self.id_ = [json getLong:@"id"];
    }
            if ([json containsKey:@"disableSubmit"])
    {
        self.disableSubmit = [json getBoolean:@"disableSubmit"];
    }
    if ([json containsKey:@"_op"])
    {
    	unichar op = [json getChar:@"_op"];
    	self->_isNew = (op == PendingCreate);
    	self->_isDirty = (op == PendingUpdate);
    	self->_isDeleted = (op == PendingDelete);
    } else {
    	self->_isNew = YES;
    	self->_isDirty = NO;
    	self->_isDeleted = NO;
    }
}

- (SUPJsonObject*)json:(int32_t)flags
{
    SUPJsonObject *newJson = [[SUPJsonObject alloc] init];
	BOOL all = YES;
	if(self.isNew)
	{
	    [newJson setChar:@"_op":PendingCreate];
	}
	else
	{
		if(self.pendingChange != NotPending && self.replayCounter > self.replayPending)
		    [newJson setChar:@"_op":self.pendingChange];
	}
	[newJson setLong:@"id":self.id_];
	if (all)
	{
	    [newJson setNullableString:@"username":self.username];
	    [newJson setNullableString:@"remoteId":self.remoteId];
	    [newJson setNullableString:@"agenteParam":self.agenteParam];
	    [newJson setBoolean:@"disableSubmit":self.disableSubmit];
	}
    [newJson setString:@"?":@"Clientes_pull_pq"];
    [newJson autorelease];
    return newJson;
}
+ (SUPObjectList*)fromJSONList:(SUPJsonArray*)jsonArray
{
	if(jsonArray == nil)
		return nil;
	
	SUPObjectList* instanceList = [[SUPObjectList alloc] initWithCapacity:1];
	if(instanceList == nil)
		return nil;

	for (SUPJsonObject* jsonObject in jsonArray)
	{
	    RHM_Comercial_Clientes_pull_pq* inst = [[RHM_Comercial_Clientes_pull_pq alloc] initFromJson:jsonObject:0];
	    [instanceList add:inst];
	    [inst release];
	}
	return instanceList;
}

+ (SUPJsonArray*)toJSONList:(SUPObjectList*)instanceList
{
	SUPJsonArray* jsonArray = [[SUPJsonArray alloc] init];
	[jsonArray autorelease];
	for (RHM_Comercial_Clientes_pull_pq* inst in instanceList)
	{
		[jsonArray add:[inst json:0]];
	}
	return jsonArray;
}
- (void)dealloc
{
    if(_username)
    {
        [_username release];
        _username = nil;
    }
    if(_remoteId)
    {
        [_remoteId release];
        _remoteId = nil;
    }
    if(_agenteParam)
    {
        [_agenteParam release];
        _agenteParam = nil;
    }
	[super dealloc];
}

- (void)bind:(id<SUPResultSetWrapper>)resultSet
{
    @try
    {
        self.username = [resultSet getNullableString:1:@"username"];
        self.remoteId = [resultSet getNullableString:2:@"remoteId"];
        self.agenteParam = [resultSet getNullableString:3:@"agenteParam"];
        self->_pending = [resultSet getBoolean:4:@"_pf"];
        self->_pendingChange = [resultSet getChar:5:@"_pc"];
        self->_replayPending = [resultSet getLong:6:@"_rp"];
        self->_replayFailure = [resultSet getLong:7:@"_rf"];
        self.id_ = [resultSet getLong:8:@"id"];
        self->_replayCounter = [resultSet getLong:9:@"_rc"];
        self.disableSubmit = [resultSet getBoolean:10:@"_ds"];
                        [self setOriginalState:nil];
        self->_originalStateValid = NO;
                                                self->_isNew = NO;
        self->_isDirty = NO;
        self->_isDeleted = NO;
    }
    @catch (SUPPersistenceException *spe)
    {
        MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"bind",[spe message]);
    }
}

- (void)clearRelationshipObjects
{
}

- (void)copyAll:(RHM_Comercial_Clientes_pull_pq*)other
{
	[self copyAll:other withParent:(SUPAbstractEntity*)other];
}


- (void)copyAll:(RHM_Comercial_Clientes_pull_pq*)other withParent:(SUPAbstractEntity*)parent
{
    [self setUsername:other.username];
    
    [self setRemoteId:other.remoteId];
    
    [self setAgenteParam:other.agenteParam];
    
    self->_pending = other->_pending;
    
    self->_pendingChange = other->_pendingChange;
    
    self->_replayPending = other->_replayPending;
    
    self->_replayFailure = other->_replayFailure;
    
    [self setId_:other.id_];
    
    self->_replayCounter = other->_replayCounter;
    
    [self setDisableSubmit:other.disableSubmit];
    
	self->_isNew = other->_isNew;

}

- (void)cancelPending
{

	[self cancelPending_OnlyReplayPending:NO:self];
}

- (void)cancelReplayPending:(SUPAbstractEntity*)entity
{

	[self cancelPending_OnlyReplayPending:YES:entity];
}

- (void)cancelPending_OnlyReplayPending:(BOOL)onlyReplayPending:(SUPAbstractEntity*)entity
{
    id<SUPConnectionWrapper> connection = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
        connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
        SUPLocalTransaction* transaction = ([connection inTransaction] ? nil : [RHM_Comercial_RHM_ComercialDB beginTransaction]);
		@try {
    		if (self.pending && (!onlyReplayPending || (self.replayCounter <= entity.replayCounter)))
    		{
        		//BOOL isDeleted = self.isDeleted;
				[self deletePending:YES];
     		}
        	if (transaction != nil)
        	{
            	[transaction commit];
        	}
    	}
    	@catch (NSException* e)
    	{
        	if (transaction != nil)
        	{
            	[transaction rollback];
        	}
        	@throw e;
    	}
    }
    @catch (SUPPersistenceException *spe)
    {
        MBOLogPersistenceException(SUPCLIENTRT_PERSISTENCEEXCEPTIONMSG,@"cancelPending",[spe message]);
    }
    @finally
    {
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    } 
}

- (void)create
{
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];    
    	self->_pendingChange = PendingCreate;
    	self->_replayCounter = 0; 
    	self->_replayFailure = 0;
    	self->_replayPending = 0;
    	if(self.id_ == 0)
    		self.id_ = [RHM_Comercial_LocalKeyGenerator generateId];

		RHM_Comercial_Clientes_pull_pq *os = [RHM_Comercial_Clientes_pull_pq getInstance];
		[os copyAll:self];
		self.originalState = os;
		//[os release];
    	[self createPending:YES];
    }
    @catch (NSException* e)
    {
        @throw e;
    }
    @finally
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];    
    }

}

- (void)delete
{
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];    
	    if (self.isNew)
	    {
	        self->_isNew = NO;
	        self->_isDeleted = YES;
	        return;
	    }
	    if (self.isCreated)
	    {
	        [self cancelPending];
	        return;
	    }
	    if (self.pendingChange == PendingDelete || self.replayPending == PendingDelete)
	    {
	        // throw new IllegalStateException("State transition error for delete operation");
	    }
	    BOOL pending = self->_pending;
	    self->_pendingChange = PendingDelete;
	    self->_replayFailure = 0;
	    self->_replayCounter = 0; 
	    self->_replayPending = 0;
	    self->_isDeleted = YES;
	    self->_pending = NO;
	    if (pending)
	    {
	        [self updatePending:YES];
	    }
	    else
	    {
	        [self createPending:YES];
	    }
	    
    }
    @catch (NSException* e)
    {
        @throw e;
    }
    @finally
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }

}

- (RHM_Comercial_RHM_ComercialDB*)database
{
   return [RHM_Comercial_RHM_ComercialDB instance];
}

+ (RHM_Comercial_Clientes_pull_pq*)find_by_id_string:(NSString*)id_string
{
    if(id_string == nil) return nil;
	int64_t key;
	NSNumberFormatter *nf = [[[NSNumberFormatter alloc] init] autorelease];
	key = [[nf numberFromString:id_string] longValue];
    return [RHM_Comercial_Clientes_pull_pq find:key];
	
}

+ (RHM_Comercial_Clientes_pull_pq*)find:(int64_t)id
{
	return [self find:id inTable:MainEntityTable];
}

+ (RHM_Comercial_Clientes_pull_pq*)find:(int64_t)id_ inTable:(SUPEntityTable)table
{
    RHM_Comercial_Clientes_pull_pq* result = nil;
	RHM_Comercial_Clientes_pull_pq* downloadState = nil;
    id<SUPStatementWrapper> preparedStatement = nil;
    id<SUPConnectionWrapper> connection = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
    
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
    	//@synchronized(connection)
    	{
        	@try
        	{
            	if (table == MainEntityTable)
            	{
                	preparedStatement = [connection prepareStatement:@"select \"username\",\"remoteId\",\"agenteParam\",\"_pf\",\"_pc\",\"_rp\",\"_rf\",\"id\",\"_rc\",\"_ds\" from rhm_comercial_1_0_clientes_pull_pq where \"id\"=? order by \"_pf\""];
            	}
            	else
            	{
                	preparedStatement = [connection prepareStatement:@"select \"username\",\"remoteId\",\"agenteParam\",\"_pf\",\"_pc\",\"_rp\",\"_rf\",\"id\",\"_rc\",\"_ds\" from rhm_comercial_1_0_clientes_pull_pq_os where \"id\"=? order by \"_pf\""];
            	}
            	[preparedStatement setLong:1:@"id":id_];
            	id<SUPResultSetWrapper> resultSet = [preparedStatement executeQuery];
            	while ([resultSet next])
            	{
            		if(result) [result release];
                	result = [[RHM_Comercial_Clientes_pull_pq alloc] init];
                	[result bind:resultSet];
                	if (table == OriginalStateEntityTable)
                	{
                    	result->_pending = false;
                    	result->_pendingChange = NotPending;
                	}
                	if (result.pending)
                	{
                    	break;
                	}
                	else
                	{
 	              		downloadState = [RHM_Comercial_Clientes_pull_pq getInstance];
                		[downloadState copyAll:result];
                	}
            	}
            	[resultSet close];      
        	}
        	@catch (SUPPersistenceException *spe)
        	{
            	@throw spe;
        	}
    	}
    }
    @catch (SUPPersistenceException *spe)
    {
        MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"find",[spe message]);
    }
    @finally
    {
    	if(preparedStatement) [preparedStatement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }
    if(result)
    {
    	if(result.pending)
    		result.downloadState = (SUPAbstractEntity*)downloadState;
  		//if(result != downloadState)
  		//	[downloadState release];
    }
    [result autorelease];
    return result;
}

+ (id<SUPSynchronizationGroup>)getSynchronizationGroup
{
	return [RHM_Comercial_RHM_ComercialDB getSyncGroupForName:@"default"];
}


- (id<SUPStatementWrapper>)getCreateStatement:(id<SUPConnectionWrapper>)connection forTable:(SUPEntityTable)table;
{
    id<SUPStatementWrapper> preparedStatement;
    if (table == MainEntityTable)
    {
        preparedStatement = [connection prepareStatement:@"insert into rhm_comercial_1_0_clientes_pull_pq (\"username\",\"remoteId\",\"agenteParam\",\"_pf\",\"_pc\",\"_rp\",\"_rf\",\"id\",\"_rc\",\"_ds\") values (?,?,?,?,?,?,?,?,?,?)"];
    }
    else
    {
        preparedStatement = [connection prepareStatement:@"insert into rhm_comercial_1_0_clientes_pull_pq_os (\"username\",\"remoteId\",\"agenteParam\",\"_pf\",\"_pc\",\"_rp\",\"_rf\",\"id\",\"_rc\",\"_ds\") values (?,?,?,?,?,?,?,?,?,?)"];
    }
    // Add updated values
    [preparedStatement setNullableString:1:@"username":self.username];
    [preparedStatement setNullableString:2:@"remoteId":self.remoteId];
    [preparedStatement setNullableString:3:@"agenteParam":self.agenteParam];
    [preparedStatement setBoolean:4:@"_pf":((table == MainEntityTable) ? self->_pending : NO)];    		
    [preparedStatement setChar:5:@"_pc":((table == MainEntityTable) ? self->_pendingChange : 'N')];    		
    [preparedStatement setLong:6:@"_rp":((table == MainEntityTable) ? self->_replayPending : 0)];    		
    [preparedStatement setLong:7:@"_rf":((table == MainEntityTable) ? self->_replayFailure : 0)];    		
    [preparedStatement setLong:8:@"id":self.id_];
    [preparedStatement setLong:9:@"_rc":((table == MainEntityTable) ? self.replayCounter : 0)];
    [preparedStatement setBoolean:10:@"_ds":self.disableSubmit];
	return preparedStatement;
}

- (id<SUPStatementWrapper>)getDeleteStatement:(id<SUPConnectionWrapper>)connection forTable:(SUPEntityTable)table;
{
    id<SUPStatementWrapper> preparedStatement;
    if (table == MainEntityTable)
    {
        preparedStatement = [connection prepareStatement:@"delete from rhm_comercial_1_0_clientes_pull_pq where \"_pf\"=? and \"id\"=?"];
    }
    else
    {
        preparedStatement = [connection prepareStatement:@"delete from rhm_comercial_1_0_clientes_pull_pq_os where \"_pf\"=? and \"id\"=?"];
    }
    // Fill in values for "where" clause
    [preparedStatement setBoolean:1:@"_pf":self->_pending];    		
    [preparedStatement setLong:2:@"id":self.id_];
	return preparedStatement;
}

- (id<SUPStatementWrapper>)getUpdateStatement:(id<SUPConnectionWrapper>)connection forTable:(SUPEntityTable)table;
{
    id<SUPStatementWrapper> preparedStatement;
    if (table == MainEntityTable)
    {
    	preparedStatement = [connection prepareStatement:@"update rhm_comercial_1_0_clientes_pull_pq set \"username\"=?,\"remoteId\"=?,\"agenteParam\"=?,\"_pc\"=?,\"_rp\"=?,\"_rf\"=?,\"_rc\"=?,\"_ds\"=? where \"_pf\"=? and \"id\"=?"];
    }
    else
    {
        preparedStatement = [connection prepareStatement:@"update rhm_comercial_1_0_clientes_pull_pq_os set \"username\"=?,\"remoteId\"=?,\"agenteParam\"=?,\"_pc\"=?,\"_rp\"=?,\"_rf\"=?,\"_rc\"=?,\"_ds\"=? where \"_pf\"=? and \"id\"=?"];
    }
    // Add updated values
    int parameterIndex = 0;
    parameterIndex++;
    [preparedStatement setNullableString:parameterIndex:@"username":self.username];
    parameterIndex++;
    [preparedStatement setNullableString:parameterIndex:@"remoteId":self.remoteId];
    parameterIndex++;
    [preparedStatement setNullableString:parameterIndex:@"agenteParam":self.agenteParam];
    parameterIndex++;
    [preparedStatement setChar:parameterIndex:@"_pc":self->_pendingChange];
    parameterIndex++;
    [preparedStatement setLong:parameterIndex:@"_rp":self->_replayPending];
    parameterIndex++;
    [preparedStatement setLong:parameterIndex:@"_rf":self->_replayFailure];
    parameterIndex++;
    [preparedStatement setLong:parameterIndex:@"_rc":self.replayCounter];
    parameterIndex++;
    [preparedStatement setBoolean:parameterIndex:@"_ds":self.disableSubmit];
    // Fill in values for "where" clause
    parameterIndex++;
    [preparedStatement setBoolean:parameterIndex:@"_pf":self->_pending];
    parameterIndex++;
    [preparedStatement setLong:parameterIndex:@"id":self.id_];
	return preparedStatement;
}

- (int64_t)_pk
{
	return [self id];
}

- (int64_t)id
{
    return self.id_;
}

- (NSString*)keyToString
{
	return [NSString stringWithFormat:@"%d",[self id]];
}

+ (void)importData:(RHM_Comercial_Clientes_pull_pq*)serverEntity:(SUPJsonObject*)jsonObject
{
	NSAutoreleasePool *importDataPool = [[NSAutoreleasePool alloc] init];
	RHM_Comercial_Clientes_pull_pq* serverEntity2 = [RHM_Comercial_Clientes_pull_pq getInstance];
    [serverEntity2 copyAll:serverEntity];
    
    if([serverEntity2 database].callbackHandler)
		[[serverEntity2 database].callbackHandler beforeImport:serverEntity2];
    if([RHM_Comercial_Clientes_pull_pq callbackHandler])
		[[RHM_Comercial_Clientes_pull_pq callbackHandler] beforeImport:serverEntity2];
	
    [serverEntity retain];
    SUPBoolean upsert = !(serverEntity.isDeleted)  && (!serverEntity.isNew) && (!serverEntity.isDirty);
    SUPBoolean create = serverEntity.isNew;
    SUPBoolean update = serverEntity.isDirty;
    SUPBoolean delete = serverEntity.isDeleted;
    
    serverEntity->_pendingChange = NotPending;
    serverEntity.replayPending = 0;
    if(upsert || create)
    {
    	@try
    	{
    		[serverEntity createPending:NO];
    	}
    	@catch(NSException *e)
    	{
    		serverEntity.isDirty = YES;
    		update = YES;
    	}
    } else if(delete)
    {
    	BOOL isCreated = NO;
    	@try
    	{
    		// check to see if server is trying to delete a newly created row
    		[serverEntity createPending:NO];
    		isCreated = YES;
    	}
    	@catch(NSException *e)
    	{
    	}
        [serverEntity deletePending:NO];
        serverEntity->_isDeleted = YES;
        serverEntity.pending = YES;
        serverEntity.pendingChange = PendingDelete;
        if(isCreated) 
        {
            RHM_Comercial_Clientes_pull_pq *clientEntity = [RHM_Comercial_Clientes_pull_pq find:[serverEntity _pk]];
            if(clientEntity != nil && clientEntity.pending)
            {
				[serverEntity refresh];
				serverEntity->_isDeleted = YES;
				serverEntity.replayCounter = 0;
				serverEntity.replayFailure = serverEntity.replayCounter;
            }
			serverEntity->_isNew = YES;
        }
    } 
	if(update)
    {
    	RHM_Comercial_Clientes_pull_pq *clientEntity = [RHM_Comercial_Clientes_pull_pq find:[serverEntity _pk]];
    	if(clientEntity.pending)
    		clientEntity = (RHM_Comercial_Clientes_pull_pq*)clientEntity.downloadState;
        @try 
        {
            [serverEntity merge:clientEntity withJson:jsonObject];
        } @catch(SUPJsonException *je)
        {
            NSException *e = [[NSException alloc] initWithName:@"SUPJsonException" reason:[je message] userInfo:nil];
            @throw e;
        }
        serverEntity.pending = NO;
        [serverEntity updatePending:NO];
        serverEntity.isDirty = YES;
        serverEntity.pending = YES;
        serverEntity.pendingChange = PendingUpdate;
    }
    if(create)
    {
        serverEntity->_isNew = YES;
        serverEntity.pending = YES;
        serverEntity.pendingChange = PendingCreate;
    }
    if([serverEntity database].callbackHandler)
		[[serverEntity database].callbackHandler onImport:serverEntity];
    if([RHM_Comercial_Clientes_pull_pq callbackHandler])
		[[RHM_Comercial_Clientes_pull_pq callbackHandler] onImport:serverEntity];

    [serverEntity release];
   
#ifdef LOGRECORD_ON_IMPORT
	[serverEntity createLogRecord:[SUPLogLevel info] withMessage:@"data import"];
#endif
	[importDataPool drain];
}

+ (RHM_Comercial_Clientes_pull_pq*)load:(int64_t)id
{
	RHM_Comercial_Clientes_pull_pq* entity = [self find:id inTable:MainEntityTable];
	//RHM_Comercial_Clientes_pull_pq* entity = [self find:id];
    if (entity == nil)
    {
		@throw [SUPObjectNotFoundException withMessage:@"-load: in RHM_Comercial_Clientes_pull_pq: entity not found in database"];
    }
    return entity;
}

static SUPEntityMetaData* RHM_Comercial_Clientes_pull_pq_META_DATA;
static BOOL _valid_ = NO;

+ (SUPEntityMetaData*)metaData
{
    if (! (_valid_))
    {
       RHM_Comercial_Clientes_pull_pq_META_DATA = [SUPEntityMetaData getInstance];
       RHM_Comercial_Clientes_pull_pq_META_DATA.id = _ENTITY_NUMBER_FOR_RHM_Comercial_Clientes_pull_pq_;
       RHM_Comercial_Clientes_pull_pq_META_DATA.name = @"Clientes_pull_pq";
       [RHM_Comercial_Clientes_pull_pq_META_DATA setClass:[RHM_Comercial_Clientes_pull_pq class]];

	   RHM_Comercial_Clientes_pull_pq_META_DATA.isClientOnly = NO;

       // Handle attributes
       
       	SUPObjectList *attributes = [SUPObjectList getInstance];
		SUPAttributeMetaData_DC* a_username = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:1:(SUPString)@"username":[SUPDataType forName:@"string?"]];
		[a_username setColumn:@"\"username\""];
		[a_username setMaxLength:300];
		[a_username setPrecision:0];
		[a_username setScale:0];
		[a_username setIsKey:NO];
		SUPAttributeMetaData_DC* a_remoteId = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:2:(SUPString)@"remoteId":[SUPDataType forName:@"string?"]];
		[a_remoteId setColumn:@"\"remoteId\""];
		[a_remoteId setMaxLength:300];
		[a_remoteId setPrecision:0];
		[a_remoteId setScale:0];
		[a_remoteId setIsKey:NO];
		SUPAttributeMetaData_DC* a_agenteParam = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:3:(SUPString)@"agenteParam":[SUPDataType forName:@"string?"]];
		[a_agenteParam setColumn:@"\"agenteParam\""];
		[a_agenteParam setMaxLength:10];
		[a_agenteParam setPrecision:0];
		[a_agenteParam setScale:0];
		[a_agenteParam setIsKey:NO];
		SUPAttributeMetaData_DC* a_pending = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:4:(SUPString)@"pending":[SUPDataType forName:@"boolean"]];
		[a_pending setColumn:@"\"_pf\""];
		[a_pending setMaxLength:-1];
		[a_pending setPrecision:0];
		[a_pending setScale:0];
		[a_pending setIsKey:NO];
		SUPAttributeMetaData_DC* a_pendingChange = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:5:(SUPString)@"pendingChange":[SUPDataType forName:@"char"]];
		[a_pendingChange setColumn:@"\"_pc\""];
		[a_pendingChange setMaxLength:1];
		[a_pendingChange setPrecision:0];
		[a_pendingChange setScale:0];
		[a_pendingChange setIsKey:NO];
		SUPAttributeMetaData_DC* a_replayPending = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:6:(SUPString)@"replayPending":[SUPDataType forName:@"long"]];
		[a_replayPending setColumn:@"\"_rp\""];
		[a_replayPending setMaxLength:-1];
		[a_replayPending setPrecision:0];
		[a_replayPending setScale:0];
		[a_replayPending setIsKey:NO];
		SUPAttributeMetaData_DC* a_replayFailure = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:7:(SUPString)@"replayFailure":[SUPDataType forName:@"long"]];
		[a_replayFailure setColumn:@"\"_rf\""];
		[a_replayFailure setMaxLength:-1];
		[a_replayFailure setPrecision:0];
		[a_replayFailure setScale:0];
		[a_replayFailure setIsKey:NO];
		SUPAttributeMetaData_DC* a_id = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:8:(SUPString)@"id":[SUPDataType forName:@"long"]];
		[a_id setColumn:@"\"id\""];
		[a_id setMaxLength:-1];
		[a_id setPrecision:0];
		[a_id setScale:0];
		[a_id setIsKey:YES];
		SUPAttributeMetaData_DC* a_replayCounter = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:9:(SUPString)@"replayCounter":[SUPDataType forName:@"long"]];
		[a_replayCounter setColumn:@"\"_rc\""];
		[a_replayCounter setMaxLength:-1];
		[a_replayCounter setPrecision:0];
		[a_replayCounter setScale:0];
		[a_replayCounter setIsKey:NO];
		SUPAttributeMetaData_DC* a_disableSubmit = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:10:(SUPString)@"disableSubmit":[SUPDataType forName:@"boolean"]];
		[a_disableSubmit setColumn:@"\"_ds\""];
		[a_disableSubmit setMaxLength:-1];
		[a_disableSubmit setPrecision:0];
		[a_disableSubmit setScale:0];
		[a_disableSubmit setIsKey:NO];
 		
 		[attributes addThis:a_username];
 		[attributes addThis:a_remoteId];
 		[attributes addThis:a_agenteParam];
 		[attributes addThis:a_pending];
 		[attributes addThis:a_pendingChange];
 		[attributes addThis:a_replayPending];
 		[attributes addThis:a_replayFailure];
 		[attributes addThis:a_id];
 		[attributes addThis:a_replayCounter];
 		[attributes addThis:a_disableSubmit];
 		RHM_Comercial_Clientes_pull_pq_META_DATA.attributes = attributes;
 		
 		SUPAttributeMap * attributeMap = [SUPAttributeMap getInstance];
    	[attributeMap setAttributes:attributes];
    	RHM_Comercial_Clientes_pull_pq_META_DATA.attributeMap = [attributeMap finishInit];
 
 		// Handle operations
 		SUPOperationMetaData* o_findAll_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:1:(SUPString)@"findAll":[SUPDataType forName:@"Clientes_pull_pq*"]:true];
		[o_findAll_0 setIsStatic:YES];
		[o_findAll_0 setIsCreate:NO];
		[o_findAll_0 setIsUpdate:NO];
		[o_findAll_0 setIsDelete:NO]; 		
 		[o_findAll_0 finishInit];
 		SUPOperationMetaData* o_findSub_2 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:2:(SUPString)@"findSub":[SUPDataType forName:@"Clientes_pull_pq?"]:true];
  		{
 			SUPObjectList *parameters_list = nil;
 			SUPParameterMetaData* p_findSub__username = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:1:(SUPString)@"_username":[SUPDataType forName:@"string?"]];
 			SUPParameterMetaData* p_findSub_agente = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:2:(SUPString)@"agente":[SUPDataType forName:@"string?"]];
 			parameters_list = [SUPObjectList listWithCapacity:2];
 			[parameters_list addThis:p_findSub__username];
 			[parameters_list addThis:p_findSub_agente];
 			o_findSub_2.parameters = parameters_list;

 		}
		[o_findSub_2 setIsStatic:YES];
		[o_findSub_2 setIsCreate:NO];
		[o_findSub_2 setIsUpdate:NO];
		[o_findSub_2 setIsDelete:NO]; 		
 		[o_findSub_2 finishInit];
 		SUPOperationMetaData* o_getPendingObjects_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:3:(SUPString)@"getPendingObjects":[SUPDataType forName:@"Clientes_pull_pq*"]:true];
		[o_getPendingObjects_0 setIsStatic:YES];
		[o_getPendingObjects_0 setIsCreate:NO];
		[o_getPendingObjects_0 setIsUpdate:NO];
		[o_getPendingObjects_0 setIsDelete:NO]; 		
 		[o_getPendingObjects_0 finishInit];
 		SUPOperationMetaData* o_getPendingObjects_1 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:4:(SUPString)@"getPendingObjects":[SUPDataType forName:@"Clientes_pull_pq*"]:true];
  		{
 			SUPObjectList *parameters_list = nil;
 			SUPParameterMetaData* p_getPendingObjects_pendingChange = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:1:(SUPString)@"pendingChange":[SUPDataType forName:@"char"]];
 			parameters_list = [SUPObjectList listWithCapacity:1];
 			[parameters_list addThis:p_getPendingObjects_pendingChange];
 			o_getPendingObjects_1.parameters = parameters_list;

 		}
		[o_getPendingObjects_1 setIsStatic:YES];
		[o_getPendingObjects_1 setIsCreate:NO];
		[o_getPendingObjects_1 setIsUpdate:NO];
		[o_getPendingObjects_1 setIsDelete:NO]; 		
 		[o_getPendingObjects_1 finishInit];
 		SUPOperationMetaData* o_getReplayPendingObjects_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:5:(SUPString)@"getReplayPendingObjects":[SUPDataType forName:@"Clientes_pull_pq*"]:true];
		[o_getReplayPendingObjects_0 setIsStatic:YES];
		[o_getReplayPendingObjects_0 setIsCreate:NO];
		[o_getReplayPendingObjects_0 setIsUpdate:NO];
		[o_getReplayPendingObjects_0 setIsDelete:NO]; 		
 		[o_getReplayPendingObjects_0 finishInit];
 		SUPOperationMetaData* o_refresh_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:6:(SUPString)@"refresh":[SUPDataType forName:@"void"]:true];
		[o_refresh_0 setIsStatic:NO];
		[o_refresh_0 setIsCreate:NO];
		[o_refresh_0 setIsUpdate:NO];
		[o_refresh_0 setIsDelete:NO]; 		
 		[o_refresh_0 finishInit];
 		SUPOperationMetaData* o__pk_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:7:(SUPString)@"_pk":[SUPDataType forName:@"long?"]:true];
		[o__pk_0 setIsStatic:NO];
		[o__pk_0 setIsCreate:NO];
		[o__pk_0 setIsUpdate:NO];
		[o__pk_0 setIsDelete:NO]; 		
 		[o__pk_0 finishInit];
 		SUPOperationMetaData* o_submitPending_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:8:(SUPString)@"submitPending":[SUPDataType forName:@"void"]:true];
		[o_submitPending_0 setIsStatic:NO];
		[o_submitPending_0 setIsCreate:NO];
		[o_submitPending_0 setIsUpdate:NO];
		[o_submitPending_0 setIsDelete:NO]; 		
 		[o_submitPending_0 finishInit];
 		SUPOperationMetaData* o_cancelPending_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:9:(SUPString)@"cancelPending":[SUPDataType forName:@"void"]:true];
		[o_cancelPending_0 setIsStatic:NO];
		[o_cancelPending_0 setIsCreate:NO];
		[o_cancelPending_0 setIsUpdate:NO];
		[o_cancelPending_0 setIsDelete:NO]; 		
 		[o_cancelPending_0 finishInit];
 		SUPOperationMetaData* o_submitPendingOperations_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:10:(SUPString)@"submitPendingOperations":[SUPDataType forName:@"void"]:true];
		[o_submitPendingOperations_0 setIsStatic:YES];
		[o_submitPendingOperations_0 setIsCreate:NO];
		[o_submitPendingOperations_0 setIsUpdate:NO];
		[o_submitPendingOperations_0 setIsDelete:NO]; 		
 		[o_submitPendingOperations_0 finishInit];
 		SUPOperationMetaData* o_cancelPendingOperations_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:11:(SUPString)@"cancelPendingOperations":[SUPDataType forName:@"void"]:true];
		[o_cancelPendingOperations_0 setIsStatic:YES];
		[o_cancelPendingOperations_0 setIsCreate:NO];
		[o_cancelPendingOperations_0 setIsUpdate:NO];
		[o_cancelPendingOperations_0 setIsDelete:NO]; 		
 		[o_cancelPendingOperations_0 finishInit];
 		SUPOperationMetaData* o_save_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:12:(SUPString)@"save":[SUPDataType forName:@"void"]:true];
		[o_save_0 setIsStatic:NO];
		[o_save_0 setIsCreate:NO];
		[o_save_0 setIsUpdate:NO];
		[o_save_0 setIsDelete:NO]; 		
 		[o_save_0 finishInit];
 		SUPOperationMetaData* o_countReplayPendingObjects_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:13:(SUPString)@"countReplayPendingObjects":[SUPDataType forName:@"int"]:true];
		[o_countReplayPendingObjects_0 setIsStatic:YES];
		[o_countReplayPendingObjects_0 setIsCreate:NO];
		[o_countReplayPendingObjects_0 setIsUpdate:NO];
		[o_countReplayPendingObjects_0 setIsDelete:NO]; 		
 		[o_countReplayPendingObjects_0 finishInit];
 
  		SUPObjectList *operations = [SUPObjectList listWithCapacity:13];
 		[operations addThis:o_findAll_0];
 		[operations addThis:o_findSub_2];
 		[operations addThis:o_getPendingObjects_0];
 		[operations addThis:o_getPendingObjects_1];
 		[operations addThis:o_getReplayPendingObjects_0];
 		[operations addThis:o_refresh_0];
 		[operations addThis:o__pk_0];
 		[operations addThis:o_submitPending_0];
 		[operations addThis:o_cancelPending_0];
 		[operations addThis:o_submitPendingOperations_0];
 		[operations addThis:o_cancelPendingOperations_0];
 		[operations addThis:o_save_0];
 		[operations addThis:o_countReplayPendingObjects_0];
 		RHM_Comercial_Clientes_pull_pq_META_DATA.operations = operations;
 		
		SUPOperationMap *operationMap = [SUPOperationMap getInstance];
		[operationMap setOperations:operations];
		RHM_Comercial_Clientes_pull_pq_META_DATA.operationMap = [operationMap finishInit];
		
		RHM_Comercial_Clientes_pull_pq_META_DATA.table = @"\"rhm_comercial_1_0_clientes_pull_pq\"";

 		[RHM_Comercial_Clientes_pull_pq_META_DATA retain];
     	_valid_ = YES;

	}
	return RHM_Comercial_Clientes_pull_pq_META_DATA;
}

- (void)merge:(RHM_Comercial_Clientes_pull_pq*)entity withJson:(SUPJsonObject*)json
{
	[super merge:entity withJson:json];
    if(![json containsKey:@"username"] )
    {
    	self.username = entity.username;
    }
    else if(![json getNullableString:@"username"])
    {
    	self.username = entity.username;
    }
    if(![json containsKey:@"remoteId"] )
    {
    	self.remoteId = entity.remoteId;
    }
    else if(![json getNullableString:@"remoteId"])
    {
    	self.remoteId = entity.remoteId;
    }
    if(![json containsKey:@"agenteParam"] )
    {
    	self.agenteParam = entity.agenteParam;
    }
    else if(![json getNullableString:@"agenteParam"])
    {
    	self.agenteParam = entity.agenteParam;
    }
    if(![json containsKey:@"id"] )
    {
    	self.id_ = entity.id_;
    }
    else if(![json getLong:@"id"])
    {
    	self.id_ = entity.id_;
    }
    if(![json containsKey:@"disableSubmit"] )
    {
    	self.disableSubmit = entity.disableSubmit;
    }
    else if(![json getBoolean:@"disableSubmit"])
    {
    	self.disableSubmit = entity.disableSubmit;
    }
}

+ (RHM_Comercial_Clientes_pull_pq*)getInstance
{
    RHM_Comercial_Clientes_pull_pq* me = [[RHM_Comercial_Clientes_pull_pq alloc] init];
    [me autorelease];
    return me;
}

- (SUPObjectList*)getLogRecords
{
    SUPQuery *query = [SUPQuery getInstance];
    [query from:@"LogRecordImpl":@"a"];
    query.testCriteria = (SUPTestCriteria*)[[SUPAttributeTest match:@"component":@"Clientes_pull_pq"] and:[SUPAttributeTest match:@"entityKey":[self keyToString]]];
    [query orderBy:@"requestId":[SUPSortOrder DESCENDING]];

    RHM_Comercial_LogRecordImplList* list = [RHM_Comercial_LogRecordImpl findWithQuery:query];
    return (SUPObjectList*)list;
}

- (id<SUPLogRecord>)createLogRecord:(int32_t)level withMessage:(NSString*)message
{
    {
        RHM_Comercial_LogRecordImpl *log = [[RHM_Comercial_LogRecordImpl alloc] init];
        //log.level = [NSString stringWithFormat:@"%ld",[SUPLogLevel fromString:level]];
        log.level = level;
        log.message = message;
        log.messageId = [RHM_Comercial_KeyGenerator generateId];
        log.requestId = [NSString stringWithFormat:@"%ld",log.messageId];
        NSDate *timestamp = [NSDate dateWithTimeIntervalSinceNow:0];
        log.timestamp = timestamp;
        log.code = CLIENT_ENTITY_CREATED_LOGRECORD_CODE;
        log.component = @"Clientes_pull_pq";
        log.entityKey = [self keyToString];
        [log save];
        [log autorelease];
        return log;
    }
}

- (void)setAllAttributesFrom:(RHM_Comercial_Clientes_pull_pq*)other
{
	// Child lists are set to nil, to prevent infinite recursion
	// when this method is used inside the bind: method
    	[self setUsername:other.username];
    	[self setRemoteId:other.remoteId];
    	[self setAgenteParam:other.agenteParam];
    	self->_pending = other->_pending;
    	self->_pendingChange = other->_pendingChange;
    	self->_replayPending = other->_replayPending;
    	self->_replayFailure = other->_replayFailure;
    	[self setId_:other.id_];
    	self->_replayCounter = other->_replayCounter;
    	[self setDisableSubmit:other.disableSubmit];
}

+ (NSObject<SUPCallbackHandler>*)callbackHandler
{
	return _callbackHandler;
}

+ (void)registerCallbackHandler:(NSObject<SUPCallbackHandler>*)newCallbackHandler
{
	if(newCallbackHandler != _callbackHandler)
	{
		[_callbackHandler release];
		_callbackHandler = [newCallbackHandler retain];
	}
}

- (void)refresh
{
    if (!self.isNew)
    {
        RHM_Comercial_Clientes_pull_pq* entity = [RHM_Comercial_Clientes_pull_pq load:[self id]];
        [self copyAll:entity];
		if(self.pending && self.pendingChange == PendingCreate)
		{
			self.originalState = self;
		}
		else
		{
			self.originalState = nil;
			self->_originalStateValid = NO;
		}
        _isNew = NO;
        _isDirty = NO;
    }
}



+ (void)replayAccepted:(SUPJsonObject*)headers withContent:(SUPJsonArray*)content
{
	for (id item in content)
    {
        SUPJsonObject* jsonObject = (SUPJsonObject*)(item);
		int64_t key;
		if ([jsonObject containsKey:@"id"]) 
		{
			key = [jsonObject getLong:@"id"];
		}
		else
		{
		    key = [jsonObject getLong:@"id"];
		}
        if ([headers containsKey:@"log"]) 
        {
            for(SUPJsonObject *o in [headers getArray:@"log"])
			{
				if(![o containsKey:@"entityKey"])
				{
					RHM_Comercial_Clientes_pull_pq* entity = [[RHM_Comercial_Clientes_pull_pq alloc] init];
					entity.id_ = key;
					[o setString:@"entityKey":[entity keyToString]];
					[entity release];
				}
				[RHM_Comercial_RHM_ComercialDB writeLogFromHeader:o:@"Clientes_pull_pq":@"replay"];
			}
        }

        RHM_Comercial_Clientes_pull_pq* clientEntity = [RHM_Comercial_Clientes_pull_pq find:key];
        if( (clientEntity != nil) && (clientEntity.pending) )
        {
            SUPLong server_id = [SUPBindUtil parseLong:[headers getString:@"id"]];
            SUPLong client_rc = [clientEntity replayPending];
            if(client_rc == server_id)
            {
				BOOL isDeleted = clientEntity.isDeleted;
            	// Server has already sent updated records, so delete the pending ones
                SUPChar pendingChange = clientEntity.pendingChange;
	            if (![RHM_Comercial_RHM_ComercialDB isSubscribed])
	            {
	            	clientEntity.replayCounter = 0;
	            	clientEntity.replayPending = 0;
	            	if(clientEntity.downloadState == nil)
	            		[clientEntity createPending:NO];
	            	else
	            		[clientEntity updatePending:NO];
	            }
	            if(isDeleted)
	            {  
	                [clientEntity deletePending:NO];
               }
                clientEntity.pending = YES;
                [clientEntity cancelReplayPending:(SUPAbstractEntity*)clientEntity];
				clientEntity->_originalState = nil;
				clientEntity->_originalStateValid = NO;
				clientEntity.pending = YES;
				clientEntity.pendingChange = pendingChange;
				clientEntity->_isNew = (pendingChange == PendingCreate);
				clientEntity->_isDirty = (pendingChange == PendingUpdate);
				clientEntity->_isDeleted = (pendingChange == PendingDelete);
				if([RHM_Comercial_Clientes_pull_pq callbackHandler])
	        		[[RHM_Comercial_Clientes_pull_pq callbackHandler] onReplaySuccess:clientEntity];       
		        if([RHM_Comercial_RHM_ComercialDB callbackHandler])
		        	[[RHM_Comercial_RHM_ComercialDB callbackHandler] onReplaySuccess:clientEntity];
            }
        }
        
    }
}



+ (void)replayRejected:(SUPJsonObject*)headers withContent:(SUPJsonArray*)content
{
    for (id item in content)
    {
        SUPJsonObject* jsonObject = (SUPJsonObject*)(item);
		int64_t key;
		if ([jsonObject containsKey:@"id"]) 
		{
			key = [jsonObject getLong:@"id"];
		}
		else
		{
		    key = [jsonObject getLong:@"id"];
		}        
        if ([headers containsKey:@"log"]) 
        {
            for(SUPJsonObject *o in [headers getArray:@"log"])
			{
				if(![o containsKey:@"entityKey"])
				{
					RHM_Comercial_Clientes_pull_pq* entity = [[RHM_Comercial_Clientes_pull_pq alloc] init];
					entity.id_ = key;
					[o setString:@"entityKey":[entity keyToString]];
					[entity release];
				}
				[RHM_Comercial_RHM_ComercialDB writeLogFromHeader:o:@"Clientes_pull_pq":@"replay"];
			}
        }
        RHM_Comercial_Clientes_pull_pq* clientEntity = [RHM_Comercial_Clientes_pull_pq find:key]; 
        [clientEntity retain];
        if(clientEntity != nil)
        {
            SUPLong server_id = [SUPBindUtil parseLong:[headers getString:@"id"]];
            SUPLong client_rc = [clientEntity replayCounter];
            if(client_rc == server_id)
            {
	        	RHM_Comercial_Clientes_pull_pq* originalState = (RHM_Comercial_Clientes_pull_pq*)clientEntity.originalState;
	        	SUPChar pendingChange = clientEntity.pendingChange;
            	[clientEntity replayRejected_childcascade];
            	clientEntity.originalState = originalState;
            	clientEntity.pending = YES;
            	clientEntity.pendingChange = pendingChange;
				clientEntity->_isNew = (pendingChange == PendingCreate);
				clientEntity->_isDirty = (pendingChange == PendingUpdate);
				clientEntity->_isDeleted = (pendingChange == PendingDelete);
			    if([RHM_Comercial_Clientes_pull_pq callbackHandler])
			    	[[RHM_Comercial_Clientes_pull_pq callbackHandler] onReplayFailure:clientEntity];
		        if([RHM_Comercial_RHM_ComercialDB callbackHandler])
		        	[[RHM_Comercial_RHM_ComercialDB callbackHandler] onReplayFailure:clientEntity];
            }
        }
        [clientEntity autorelease];
     }
}



-(void)submitPending
{
	[self submitPending1:YES];
}

-(void)submitPendingNoRefresh
{
	[self submitPending1:NO];
}

-(void)submitPending1:(BOOL)doRefresh
{
    id<SUPConnectionWrapper> connection = nil;
    SUPLocalTransaction* transaction = nil;
    BOOL success = NO;
    SUPJsonMessage* message = nil;
    
    //if(_disableSubmit)
    //    return;
    //if(_replayPending == _replayCounter) // already submitted
    //	return;
    @try
    {
        message = [[SUPJsonMessage alloc] init];
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];    
        connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
        transaction = ([connection inTransaction] ? nil : [RHM_Comercial_RHM_ComercialDB beginTransaction]);
    	if(doRefresh)
	        [self refresh];
        if (self.pending && !self.disableSubmit && (self.replayCounter > self.replayPending))
        {
            SUPJsonObject* headers = [message headers];
            [headers setString:@"pkg":@"RHM_Comercial:1.0"];
            [headers setString:@"mbo":@"Clientes_pull_pq"];
            [headers setString:@"method":@"replay"];
            [headers setString:@"id":[SUPStringUtil toString_long:self.replayCounter]];

			
            [message setContent:[self json:2]];
            
            self.replayFailure = 0;
            self.replayCounter = 0;
            self.replayPending = self.replayCounter;
            [self updatePending:YES];
        }
        if (transaction != nil)
        {
            [transaction commit];
        }
        success = YES;
    }
    @catch (NSException* e)
    {
        if (transaction != nil)
        {
            [transaction rollback];
        }
        success = NO;
        @throw e;
    }
    @finally
    {
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
        if(success)
            [RHM_Comercial_RHM_ComercialDB replay:@"Clientes_pull_pq" withId:self.replayCounter withContent:[message content]];
        [message release];
    }
}

- (void)submitPending_save_childcascade:(SUPAbstractEntity*)parent
{
	if([self pending])
	{
		self->_replayCounter = parent->_replayCounter;
		[self updatePending:YES];
    }
}

- (void)submitPending_update_childcascade:(SUPAbstractEntity*)parent
{
    if ([self pending])
    {
        //BOOL isCreate = [self isCreated];
	    self.replayFailure = 0;
	    self.replayPending = self.replayCounter;
	    [self updatePending:YES];
        //if(!isCreate)
        //    [self updateOriginalState];
    }        

}

 
+ (void)submitPendingOperations
{
	[super submitPendingOperations];
}

+ (void)cancelPendingOperations
{
	[super cancelPendingOperations];
}

- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	Clientes_pull_pq = \n\
	    username = %@,\n\
	    remoteId = %@,\n\
	    agenteParam = %@,\n\
	    pending = %i,\n\
	    pendingChange = %c,\n\
	    replayPending = %qi,\n\
	    replayFailure = %qi,\n\
	    id = %qi,\n\
	    replayCounter = %qi,\n\
	    disableSubmit = %i,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.username
    	,self.remoteId
    	,self.agenteParam
    	,self->_pending
    	,self->_pendingChange
    	,self->_replayPending
    	,self->_replayFailure
    	,self.id_
    	,self->_replayCounter
    	,self.disableSubmit
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}

- (void)save
{
    if (self->_isNew)
    {
        [self create];
    }
    else if (self->_isDirty)
    {
        [self update];
    }
}


- (void)createPending:(BOOL)isPending
{
   	id<SUPConnectionWrapper> connection = nil;
    id<SUPStatementWrapper> statement = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
    	self->_pending = isPending;
    	if(!isPending)
    	{
    		self->_replayPending = 0;
    		self->_replayFailure = 0;
    	}
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
    	statement = [self getCreateStatement:connection forTable:MainEntityTable];
		[statement executeInsert];
		self->_isNew = NO;
		self->_isDirty = NO;
		self->_isDeleted = NO;
		if (isPending)
		{
			RHM_Comercial_Clientes_pull_pq* originalEntity = (RHM_Comercial_Clientes_pull_pq*)[self originalState];
			if (originalEntity != nil)
			{
				originalEntity.pending = NO;
				id<SUPStatementWrapper> os_statement = [originalEntity getCreateStatement:connection forTable:OriginalStateEntityTable];
				[os_statement executeInsert];
				[os_statement close];					
			}
		}
    	self->_pending = isPending;
	}
	@catch (SUPPersistenceException *spe)
    {
        //MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"createPending",[spe message]);
    	@throw spe;
    }
    @finally
    {
		[statement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }    
}

- (void)updatePending:(BOOL)isPending
{
   	id<SUPConnectionWrapper> connection = nil;
   	id<SUPStatementWrapper> statement = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
    	self->_pending = isPending;
		if(!isPending)
    	{
    		self->_replayPending = 0;
    		self->_replayFailure = 0;
    	}
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
    	statement = [self getUpdateStatement:connection forTable:MainEntityTable];
		[statement executeUpdate:YES];
		self->_isNew = NO;
		self->_isDirty = NO;
		self->_isDeleted = NO;
	}
	@catch (SUPPersistenceException *spe)
    {
        //MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"updatePending",[spe message]);
		@throw spe;
    }
    @finally
    {
		[statement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }    	
}

- (SUPAbstractEntity*)originalState
{
    if (!self->_originalStateValid)
    {
        self->_originalState = self.pending ? [RHM_Comercial_Clientes_pull_pq find:[self id] inTable:OriginalStateEntityTable] : nil;
        if(self->_originalState == nil && !self.isCreated) self->_originalState = self.downloadState;
        //if(self->_originalState != self) [self->_originalState retain];
        self->_originalStateValid = YES;
    }
    return (SUPAbstractEntity*)(self->_originalState);
}

- (SUPAbstractEntity*)downloadState
{
    if (!self->_downloadStateValid)
    {
        if(self.isNew) 
        {
            self->_downloadState = nil;
        }
        else if(self.pending)
        {
            RHM_Comercial_Clientes_pull_pq *mbo = [RHM_Comercial_Clientes_pull_pq find:[self id]];
            if(mbo)
                self->_downloadState = mbo->_downloadState;
            else
                self->_downloadState = nil;
        }
        else
        {
            self->_downloadState = nil;
        }
        self->_downloadStateValid = YES;
    }
    return (SUPAbstractEntity*)(self->_downloadState);
}


- (void)updateOriginalState
{
   	id<SUPConnectionWrapper> connection = nil;
	id<SUPStatementWrapper> statement = nil;
	BOOL savePending = self->_pending;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		self->_pending = NO;
			
		RHM_Comercial_Clientes_pull_pq* os = [RHM_Comercial_Clientes_pull_pq find:[self id] inTable:OriginalStateEntityTable];
		if(os)
		{
			statement = [self getUpdateStatement:connection forTable:OriginalStateEntityTable];
			[statement executeUpdate:YES];
		} else {
			statement = [self getCreateStatement:connection forTable:OriginalStateEntityTable];
			[statement executeInsert];
		}
		self->_originalStateValid = NO;
	}
	@catch (SUPPersistenceException *spe)
	{
		MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"updateOriginalState",[spe message]);
	}
    @finally
    {
		self->_pending = savePending;
		[statement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }    
    			
}


- (SUPAbstractEntity*)topLevelParent
{
	return self;
}

- (void)update
{
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
	    if (self.isDirty)
    	{
        	BOOL pending = self.pending;
            if(self.pendingChange == PendingCreate && self.replayPending > 0) // already submitted
                self->_pendingChange = PendingUpdate;
        	else if (self.pendingChange != PendingCreate && self.pendingChange != PendingDelete)
        	{
        	    self->_pendingChange = PendingUpdate;
        	}
        	self->_replayFailure = 0;
        	self->_replayCounter = 0;
        	if (pending)
        	{
        	    [self updatePending:YES];
        	}
        	else
        	{
        	    [self createPending:YES];
        	}
        }
    }
    @catch (NSException* e)
    {
        @throw e;
    }
    @finally
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }

}




+ (SUPObjectList*)findAll
{
	return [self findAll:0 take:-1]; 
}


	

+ (SUPObjectList*)findAll:(int32_t)skip take:(int32_t)take
{
	SUPObjectList* result = [[[SUPObjectList alloc] init] autorelease];
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:322];
	    [sql appendString:@"select s.\"username\",s.\"remoteId\",s.\"agenteParam\",s.\"_pf\",s.\"_pc\",s.\"_rp\",s.\"_rf\",s.\"id\",s.\"_rc\",s.\"_ds\" from \"rhm_comercial_1_0_clientes_pull_pq\" s where (((s.\"_pf\" = 1 or not exists (select s_os.\"id\" from \"rhm_comercial_1_0_clientes_pull_pq_os\" s_os where s_os.\"id\" = s"
	                            ".\"id\"))))"];
	    if(take != -1)
	        [sql appendFormat:@" limit %i",take];
	    if(skip != 0)
	        [sql appendFormat:@" offset %i",skip];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        RHM_Comercial_Clientes_pull_pq* entity = [[RHM_Comercial_Clientes_pull_pq alloc] init];
	        [entity bind:resultSet];
	        [result add:entity];
			[entity release];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"findAll",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}



+ (RHM_Comercial_Clientes_pull_pq*)findSub:(NSString*)_username withAgente:(NSString*)agente
{
	RHM_Comercial_Clientes_pull_pq* result = nil;
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:441];
	    [sql appendString:@"select s.\"username\",s.\"remoteId\",s.\"agenteParam\",s.\"_pf\",s.\"_pc\",s.\"_rp\",s.\"_rf\",s.\"id\",s.\"_rc\",s.\"_ds\" from \"rhm_comercial_1_0_clientes_pull_pq\" s where (((s.\"_pf\" = 1 or not exists (select s_os.\"id\" from \"rhm_comercial_1_0_clientes_pull_pq_os\" s_os where s_os.\"id\" = s"
	                            ".\"id\")))) and ( s.\"username\" =? and ( s.\"agenteParam\"=? or (s.\"agenteParam\" IS NULL AND CAST(? AS varchar(100)) IS NULL)))"];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    [preparedStatement setNullableString:1:@"_username":_username];
	    [preparedStatement setNullableString:2:@"agente":agente];
	    [preparedStatement setNullableString:3:@"agente":agente];
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        RHM_Comercial_Clientes_pull_pq* entity = [[RHM_Comercial_Clientes_pull_pq alloc] init];
	        [entity bind:resultSet];
	        result = [entity autorelease];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"findSub",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}



+ (SUPObjectList*)getPendingObjects
{
	return [self getPendingObjects:0 take:-1]; 
}


	

+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take
{
	SUPObjectList* result = [[[SUPObjectList alloc] init] autorelease];
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:223];
	    [sql appendString:@"select x.\"username\",x.\"remoteId\",x.\"agenteParam\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"id\",x.\"_rc\",x.\"_ds\" from \"rhm_comercial_1_0_clientes_pull_pq\" x where x.\"_pc\" <> \'N\' and x.\"_rc\" != x.\"_rp\""];
	    if(take != -1)
	        [sql appendFormat:@" limit %i",take];
	    if(skip != 0)
	        [sql appendFormat:@" offset %i",skip];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        RHM_Comercial_Clientes_pull_pq* entity = [[RHM_Comercial_Clientes_pull_pq alloc] init];
	        [entity bind:resultSet];
	        [result add:entity];
			[entity release];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"getPendingObjects",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}



+ (SUPObjectList*)getPendingObjects:(unichar)pendingChange
{
	return [self getPendingObjects:pendingChange skip:0 take:-1]; 
}


	

+ (SUPObjectList*)getPendingObjects:(unichar)pendingChange skip:(int32_t)skip take:(int32_t)take
{
	SUPObjectList* result = [[[SUPObjectList alloc] init] autorelease];
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:218];
	    [sql appendString:@"select x.\"username\",x.\"remoteId\",x.\"agenteParam\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"id\",x.\"_rc\",x.\"_ds\" from \"rhm_comercial_1_0_clientes_pull_pq\" x where x.\"_pc\" = ? and x.\"_rc\" != x.\"_rp\""];
	    if(take != -1)
	        [sql appendFormat:@" limit %i",take];
	    if(skip != 0)
	        [sql appendFormat:@" offset %i",skip];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    [preparedStatement setChar:1:@"pendingChange":pendingChange];
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        RHM_Comercial_Clientes_pull_pq* entity = [[RHM_Comercial_Clientes_pull_pq alloc] init];
	        [entity bind:resultSet];
	        [result add:entity];
			[entity release];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"getPendingObjects",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}



+ (SUPObjectList*)getReplayPendingObjects
{
	return [self getReplayPendingObjects:0 take:-1]; 
}


	

+ (SUPObjectList*)getReplayPendingObjects:(int32_t)skip take:(int32_t)take
{
	SUPObjectList* result = [[[SUPObjectList alloc] init] autorelease];
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:344];
	    [sql appendString:@"select x.\"username\",x.\"remoteId\",x.\"agenteParam\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"id\",x.\"_rc\",x.\"_ds\" from \"rhm_comercial_1_0_clientes_pull_pq\" x where (((x.\"_pf\" = 1 or not exists (select x_os.\"id\" from \"rhm_comercial_1_0_clientes_pull_pq_os\" x_os where x_os.\"id\" = x"
	                            ".\"id\")))) and ( x.\"_rp\" != 0)"];
	    if(take != -1)
	        [sql appendFormat:@" limit %i",take];
	    if(skip != 0)
	        [sql appendFormat:@" offset %i",skip];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        RHM_Comercial_Clientes_pull_pq* entity = [[RHM_Comercial_Clientes_pull_pq alloc] init];
	        [entity bind:resultSet];
	        [result add:entity];
			[entity release];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"getReplayPendingObjects",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}



+ (int32_t)countReplayPendingObjects
{
	int32_t result;
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:237];
	    [sql appendString:@"select count(*) ,x.\"id\" from \"rhm_comercial_1_0_clientes_pull_pq\" x where (((x.\"_pf\" = 1 or not exists (select x_os.\"id\" from \"rhm_comercial_1_0_clientes_pull_pq_os\" x_os where x_os.\"id\" = x.\"id\")))) and ( x.\"_rp\" != 0)"];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        result = [resultSet getInt:1:@""];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"countReplayPendingObjects",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}

@end