/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.0.1.314
*/ 

#import "RHM_Comercial_LogRecordImpl.h"
#import "SUPJsonObject.h"
#import "SUPJsonArray.h"
#import "SUPJsonMessage.h"
#import "SUPJsonReader.h"
#import "SUPConnectionWrapper.h"
#import "SUPLocalTransaction.h"
#import "SUPObjectNotFoundException.h"
#import "SUPNoSuchOperationException.h"
#import "SUPQuery.h"
#import "SUPQueueConnection.h"
#import "SUPResultSetWrapper.h"
#import "SUPStatementWrapper.h"
#import "SUPStatementBuilder.h"
#import "SUPEntityMetaData.h"
#import "SUPOperationMetaData.h"
#import "SUPAttributeMetaData.h"
#import "SUPAttributeMetaData_DC.h"
#import "SUPDatabaseMetaData.h"
#import "SUPSelectItem.h"
#import "SUPAttributeMap.h"
#import "SUPOperationMap.h"
#import "SUPDataType.h"
#import "MBODebugLogger.h"
#import "RHM_Comercial_RHM_ComercialDB.h"
#import "RHM_Comercial_KeyGenerator.h"
#import "RHM_Comercial_LocalKeyGenerator.h"
#import "RHM_Comercial_KeyGeneratorPK.h"
#import "RHM_Comercial_LocalKeyGeneratorPK.h"
#import "SUPCallbackHandler.h"
#import "RHM_Comercial_Clientes.h"
#import "MBODebugSettings.h"
#import "SUPEntityAlias.h"

static NSObject<SUPCallbackHandler>* _callbackHandler = nil;

@interface RHM_Comercial_LogRecordImpl(private)
- (void)bind:(id<SUPResultSetWrapper>)resultSet;
- (void)bindWithQuery:(id<SUPResultSetWrapper>)resultSet:(SUPQuery*)query;
+ (RHM_Comercial_LogRecordImpl*)find:(int64_t)id inTable:(SUPEntityTable)table;
+ (void)importData:(RHM_Comercial_LogRecordImpl*)serverEntity:(SUPJsonObject*)jsonObject;
- (void)merge:(RHM_Comercial_LogRecordImpl*)entity withJson:(SUPJsonObject*)json;
- (void)setAllAttributesFrom:(RHM_Comercial_LogRecordImpl*)other;
@end
@implementation RHM_Comercial_LogRecordImpl

@synthesize level = _level;
@synthesize code = _code;
@synthesize eisCode = _eisCode;
@synthesize message = _message;
@synthesize component = _component;
@synthesize entityKey = _entityKey;
@synthesize operation = _operation;
@synthesize requestId = _requestId;
@synthesize timestamp = _timestamp;
@synthesize messageId = _messageId;

- (int64_t)messageId
{
    if (_messageId == 0)
        _messageId = (int64_t)[RHM_Comercial_KeyGenerator generateId];
    return _messageId;
}

- (void)setLevel:(int32_t)newLevel
{
    if (newLevel != self->_level)
    {
        self->_level = newLevel;
        self->_isDirty = YES;
    }
}

- (void)setCode:(int32_t)newCode
{
    if (newCode != self->_code)
    {
        self->_code = newCode;
        self->_isDirty = YES;
    }
}

- (void)setEisCode:(NSString*)newEisCode
{
    if (newEisCode != self->_eisCode)
    {
		[self->_eisCode release];
        self->_eisCode = [newEisCode retain];
        self->_isDirty = YES;
    }
}

- (void)setMessage:(NSString*)newMessage
{
    if (newMessage != self->_message)
    {
		[self->_message release];
        self->_message = [newMessage retain];
        self->_isDirty = YES;
    }
}

- (void)setComponent:(NSString*)newComponent
{
    if (newComponent != self->_component)
    {
		[self->_component release];
        self->_component = [newComponent retain];
        self->_isDirty = YES;
    }
}

- (void)setEntityKey:(NSString*)newEntityKey
{
    if (newEntityKey != self->_entityKey)
    {
		[self->_entityKey release];
        self->_entityKey = [newEntityKey retain];
        self->_isDirty = YES;
    }
}

- (void)setOperation:(NSString*)newOperation
{
    if (newOperation != self->_operation)
    {
		[self->_operation release];
        self->_operation = [newOperation retain];
        self->_isDirty = YES;
    }
}

- (void)setRequestId:(NSString*)newRequestId
{
    if (newRequestId != self->_requestId)
    {
		[self->_requestId release];
        self->_requestId = [newRequestId retain];
        self->_isDirty = YES;
    }
}

- (void)setTimestamp:(NSDate*)newTimestamp
{
    if (newTimestamp != self->_timestamp)
    {
		[self->_timestamp release];
        self->_timestamp = [newTimestamp retain];
        self->_isDirty = YES;
    }
}

- (void)setMessageId:(int64_t)newMessageId
{
    if (newMessageId != self->_messageId)
    {
        self->_messageId = newMessageId;
        self->_isNew = YES;
    }
}


- (SUPLong)replayCounter
{
    if ((_replayCounter == 0))
    {  
        _replayCounter = ((SUPLong)([RHM_Comercial_LocalKeyGenerator generateId]));
    }
    return _replayCounter;
}

- (void)setReplayCounter:(SUPLong)newReplayCounter
{
    if (! ((_replayCounter == newReplayCounter)))
    {  
        self->_isDirty = YES;
        _replayCounter = newReplayCounter;
    }
}

- (id)initFromJson:(SUPJsonObject*)json:(int32_t)flags
{
    if (json == nil)
    {
        [self release];
        return nil;
    }
    if ((self = [super init]))
    {
        [self readJson:json:flags];
    }
    return self;   
}

- (void)readJson:(SUPJsonObject*)json:(int32_t)flags
{
        if ([json containsKey:@"level"])
    {
        self.level = [json getInt:@"level"];
    }
        if ([json containsKey:@"code"])
    {
        self.code = [json getInt:@"code"];
    }
        if ([json containsKey:@"eisCode"])
    {
        self.eisCode = [json getNullableString:@"eisCode"];
    }
        if ([json containsKey:@"message"])
    {
        self.message = [json getNullableString:@"message"];
    }
        if ([json containsKey:@"component"])
    {
        self.component = [json getNullableString:@"component"];
    }
        if ([json containsKey:@"entityKey"])
    {
        self.entityKey = [json getNullableString:@"entityKey"];
    }
        if ([json containsKey:@"operation"])
    {
        self.operation = [json getNullableString:@"operation"];
    }
        if ([json containsKey:@"requestId"])
    {
        self.requestId = [json getNullableString:@"requestId"];
    }
        if ([json containsKey:@"timestamp"])
    {
        self.timestamp = [SUPDateTimeUtil getNullableDateTime_s:[json getNullableString:@"timestamp"]];
    }
                        if ([json containsKey:@"messageId"])
    {
        self.messageId = [json getLong:@"messageId"];
    }
            if ([json containsKey:@"disableSubmit"])
    {
        self.disableSubmit = [json getBoolean:@"disableSubmit"];
    }
    if ([json containsKey:@"_op"])
    {
    	unichar op = [json getChar:@"_op"];
    	self->_isNew = (op == PendingCreate);
    	self->_isDirty = (op == PendingUpdate);
    	self->_isDeleted = (op == PendingDelete);
    } else {
    	self->_isNew = YES;
    	self->_isDirty = NO;
    	self->_isDeleted = NO;
    }
}

- (SUPJsonObject*)json:(int32_t)flags
{
    SUPJsonObject *newJson = [[SUPJsonObject alloc] init];
	BOOL all = YES;
	if(self.isNew)
	{
	    [newJson setChar:@"_op":PendingCreate];
	}
	else
	{
		if(self.pendingChange != NotPending && self.replayCounter > self.replayPending)
		    [newJson setChar:@"_op":self.pendingChange];
	}
	[newJson setLong:@"messageId":self.messageId];
	if (all)
	{
	    [newJson setInt:@"level":self.level];
	    [newJson setInt:@"code":self.code];
	    [newJson setNullableString:@"eisCode":self.eisCode];
	    [newJson setNullableString:@"message":self.message];
	    [newJson setNullableString:@"component":self.component];
	    [newJson setNullableString:@"entityKey":self.entityKey];
	    [newJson setNullableString:@"operation":self.operation];
	    [newJson setNullableString:@"requestId":self.requestId];
	    [newJson setNullableDateTime:@"timestamp":self.timestamp];
	    [newJson setBoolean:@"disableSubmit":self.disableSubmit];
	}
    [newJson setString:@"?":@"LogRecordImpl"];
    [newJson autorelease];
    return newJson;
}
+ (SUPObjectList*)fromJSONList:(SUPJsonArray*)jsonArray
{
	if(jsonArray == nil)
		return nil;
	
	SUPObjectList* instanceList = [[SUPObjectList alloc] initWithCapacity:1];
	if(instanceList == nil)
		return nil;

	for (SUPJsonObject* jsonObject in jsonArray)
	{
	    RHM_Comercial_LogRecordImpl* inst = [[RHM_Comercial_LogRecordImpl alloc] initFromJson:jsonObject:0];
	    [instanceList add:inst];
	    [inst release];
	}
	return instanceList;
}

+ (SUPJsonArray*)toJSONList:(SUPObjectList*)instanceList
{
	SUPJsonArray* jsonArray = [[SUPJsonArray alloc] init];
	[jsonArray autorelease];
	for (RHM_Comercial_LogRecordImpl* inst in instanceList)
	{
		[jsonArray add:[inst json:0]];
	}
	return jsonArray;
}
- (void)dealloc
{
    if(_eisCode)
    {
        [_eisCode release];
        _eisCode = nil;
    }
    if(_message)
    {
        [_message release];
        _message = nil;
    }
    if(_component)
    {
        [_component release];
        _component = nil;
    }
    if(_entityKey)
    {
        [_entityKey release];
        _entityKey = nil;
    }
    if(_operation)
    {
        [_operation release];
        _operation = nil;
    }
    if(_requestId)
    {
        [_requestId release];
        _requestId = nil;
    }
    if(_timestamp)
    {
        [_timestamp release];
        _timestamp = nil;
    }
	[super dealloc];
}

- (void)bind:(id<SUPResultSetWrapper>)resultSet
{
    @try
    {
        self.level = [resultSet getInt:1:@"e"];
        self.code = [resultSet getInt:2:@"f"];
        self.eisCode = [resultSet getNullableString:3:@"g"];
        self.message = [resultSet getNullableString:4:@"h"];
        self.component = [resultSet getNullableString:5:@"i"];
        self.entityKey = [resultSet getNullableString:6:@"j"];
        self.operation = [resultSet getNullableString:7:@"l"];
        self.requestId = [resultSet getNullableString:8:@"m"];
        self.timestamp = [resultSet getNullableDateTime:9:@"n"];
        self->_pending = [resultSet getBoolean:10:@"_pf"];
        self->_pendingChange = [resultSet getChar:11:@"_pc"];
        self->_replayPending = [resultSet getLong:12:@"_rp"];
        self->_replayFailure = [resultSet getLong:13:@"_rf"];
        self.messageId = [resultSet getLong:14:@"d"];
        self->_replayCounter = [resultSet getLong:15:@"_rc"];
        self.disableSubmit = [resultSet getBoolean:16:@"_ds"];
                        [self setOriginalState:nil];
        self->_originalStateValid = NO;
                                                self->_isNew = NO;
        self->_isDirty = NO;
        self->_isDeleted = NO;
    }
    @catch (SUPPersistenceException *spe)
    {
        MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"bind",[spe message]);
    }
}

- (void)bindWithQuery:(id<SUPResultSetWrapper>)resultSet:(SUPQuery*)query
{

    SUPDatabaseMetaData *database = [RHM_Comercial_RHM_ComercialDB metaData];
    SUPEntityMetaData *entity = [RHM_Comercial_LogRecordImpl metaData];
    SUPObjectList* cl = [SUPObjectList listWithCapacity:10];
    
    if(query.selectItems != nil)
    {
    	for (SUPSelectItem* si in query.selectItems)
    	{
        	SUPEntityMetaData* itemEntity = [SUPStatementBuilder findEntity:database:query:si.alias];
        	SUPAttributeMetaData* amd = [itemEntity getAttribute:si.attribute];
        	[cl add:amd];
    	}
    } else 
    {
        for (SUPAttributeMetaData* amd in entity.attributes)
        {
            if ([amd isPersistent])
            {
                [cl add:amd];
            }
        }
    }
    self->_isNew = NO;
    self->_isDirty = NO;
    
    for(int j=0;j<[cl size];j++)
    {
        SUPAttributeMetaData *amd = (SUPAttributeMetaData *)[cl item:j];
		if([amd.name isEqualToString:@"level"])
        	self.level = [resultSet getInt:j+1:@"e"];
		if([amd.name isEqualToString:@"code"])
        	self.code = [resultSet getInt:j+1:@"f"];
		if([amd.name isEqualToString:@"eisCode"])
        	self.eisCode = [resultSet getNullableString:j+1:@"g"];
		if([amd.name isEqualToString:@"message"])
        	self.message = [resultSet getNullableString:j+1:@"h"];
		if([amd.name isEqualToString:@"component"])
        	self.component = [resultSet getNullableString:j+1:@"i"];
		if([amd.name isEqualToString:@"entityKey"])
        	self.entityKey = [resultSet getNullableString:j+1:@"j"];
		if([amd.name isEqualToString:@"operation"])
        	self.operation = [resultSet getNullableString:j+1:@"l"];
		if([amd.name isEqualToString:@"requestId"])
        	self.requestId = [resultSet getNullableString:j+1:@"m"];
		if([amd.name isEqualToString:@"timestamp"])
        	self.timestamp = [resultSet getNullableDateTime:j+1:@"n"];
		if([amd.name isEqualToString:@"pending"])
        	self->_pending = [resultSet getBoolean:j+1:@"_pf"];
		if([amd.name isEqualToString:@"pendingChange"])
        	self->_pendingChange = [resultSet getChar:j+1:@"_pc"];
		if([amd.name isEqualToString:@"replayPending"])
        	self->_replayPending = [resultSet getLong:j+1:@"_rp"];
		if([amd.name isEqualToString:@"replayFailure"])
        	self->_replayFailure = [resultSet getLong:j+1:@"_rf"];
		if([amd.name isEqualToString:@"messageId"])
        	self.messageId = [resultSet getLong:j+1:@"d"];
		if([amd.name isEqualToString:@"replayCounter"])
        	self->_replayCounter = [resultSet getLong:j+1:@"_rc"];
		if([amd.name isEqualToString:@"disableSubmit"])
        	self.disableSubmit = [resultSet getBoolean:j+1:@"_ds"];
    }
    self->_isNew = NO;
    self->_isDirty = NO;
    self->_isDeleted = NO;
}

- (void)clearRelationshipObjects
{
}

- (void)copyAll:(RHM_Comercial_LogRecordImpl*)other
{
	[self copyAll:other withParent:(SUPAbstractEntity*)other];
}


- (void)copyAll:(RHM_Comercial_LogRecordImpl*)other withParent:(SUPAbstractEntity*)parent
{
    [self setLevel:other.level];
    
    [self setCode:other.code];
    
    [self setEisCode:other.eisCode];
    
    [self setMessage:other.message];
    
    [self setComponent:other.component];
    
    [self setEntityKey:other.entityKey];
    
    [self setOperation:other.operation];
    
    [self setRequestId:other.requestId];
    
    [self setTimestamp:other.timestamp];
    
    self->_pending = other->_pending;
    
    self->_pendingChange = other->_pendingChange;
    
    self->_replayPending = other->_replayPending;
    
    self->_replayFailure = other->_replayFailure;
    
    [self setMessageId:other.messageId];
    
    self->_replayCounter = other->_replayCounter;
    
    [self setDisableSubmit:other.disableSubmit];
    
	self->_isNew = other->_isNew;

}

+ (int32_t)countWithQuery:(SUPQuery*)query
{
    id<SUPConnectionWrapper> connection = nil;
id<SUPStatementWrapper> statement = nil;
id<SUPResultSetWrapper> resultSet = nil;
    {
        @try
        {    
            [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
            connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
            int32_t count = 0;

            statement = [SUPStatementBuilder prepareQuery:connection:[RHM_Comercial_RHM_ComercialDB metaData]:[RHM_Comercial_LogRecordImpl metaData]:query];
            resultSet = [statement executeQuery];
            while ([resultSet next])
            {
                count++;   
            }
			return count;
        }
        @catch (NSException *e)
        {
                    MBOLogPersistenceException(SUPCLIENTRT_PERSISTENCEEXCEPTIONMSG, @"countWithQuery",[NSString stringWithFormat:@"%@: %@",[e name],[e reason]]);
        }
        @finally
        {
            if(resultSet) [resultSet close];
            if(statement) [statement close];
            [connection releaseToPool];
            [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
        }
    }
	return 0;
}

- (void)cancelPending
{

	[self cancelPending_OnlyReplayPending:NO:self];
}

- (void)cancelReplayPending:(SUPAbstractEntity*)entity
{

	[self cancelPending_OnlyReplayPending:YES:entity];
}

- (void)cancelPending_OnlyReplayPending:(BOOL)onlyReplayPending:(SUPAbstractEntity*)entity
{
    id<SUPConnectionWrapper> connection = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
        connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
        SUPLocalTransaction* transaction = ([connection inTransaction] ? nil : [RHM_Comercial_RHM_ComercialDB beginTransaction]);
		@try {
    		if (self.pending && (!onlyReplayPending || (self.replayCounter <= entity.replayCounter)))
    		{
        		//BOOL isDeleted = self.isDeleted;
				[self deletePending:YES];
     		}
        	if (transaction != nil)
        	{
            	[transaction commit];
        	}
    	}
    	@catch (NSException* e)
    	{
        	if (transaction != nil)
        	{
            	[transaction rollback];
        	}
        	@throw e;
    	}
    }
    @catch (SUPPersistenceException *spe)
    {
        MBOLogPersistenceException(SUPCLIENTRT_PERSISTENCEEXCEPTIONMSG,@"cancelPending",[spe message]);
    }
    @finally
    {
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    } 
}

- (void)create
{
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];    
    	self->_pendingChange = PendingCreate;
    	self->_replayCounter = 0; 
    	self->_replayFailure = 0;
    	self->_replayPending = 0;
    	if(self.messageId == 0)
    		self.messageId = [RHM_Comercial_LocalKeyGenerator generateId];

		RHM_Comercial_LogRecordImpl *os = [RHM_Comercial_LogRecordImpl getInstance];
		[os copyAll:self];
		self.originalState = os;
		//[os release];
    	[self createPending:YES];
    }
    @catch (NSException* e)
    {
        @throw e;
    }
    @finally
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];    
    }

}

- (void)delete
{
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];    
	    if (self.isNew)
	    {
	        self->_isNew = NO;
	        self->_isDeleted = YES;
	        return;
	    }
	    if (self.isCreated)
	    {
	        [self cancelPending];
	        return;
	    }
	    if (self.pendingChange == PendingDelete || self.replayPending == PendingDelete)
	    {
	        // throw new IllegalStateException("State transition error for delete operation");
	    }
	    BOOL pending = self->_pending;
	    self->_pendingChange = PendingDelete;
	    self->_replayFailure = 0;
	    self->_replayCounter = 0; 
	    self->_replayPending = 0;
	    self->_isDeleted = YES;
	    self->_pending = NO;
	    if (pending)
	    {
	        [self updatePending:YES];
	    }
	    else
	    {
	        [self createPending:YES];
	    }
	    
    }
    @catch (NSException* e)
    {
        @throw e;
    }
    @finally
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }

}

- (RHM_Comercial_RHM_ComercialDB*)database
{
   return [RHM_Comercial_RHM_ComercialDB instance];
}

+ (RHM_Comercial_LogRecordImpl*)find_by_id_string:(NSString*)id_string
{
    if(id_string == nil) return nil;
	int64_t key;
	NSNumberFormatter *nf = [[[NSNumberFormatter alloc] init] autorelease];
	key = [[nf numberFromString:id_string] longValue];
    return [RHM_Comercial_LogRecordImpl find:key];
	
}

+ (RHM_Comercial_LogRecordImpl*)find:(int64_t)id
{
	return [self find:id inTable:MainEntityTable];
}

+ (RHM_Comercial_LogRecordImpl*)find:(int64_t)id_ inTable:(SUPEntityTable)table
{
    RHM_Comercial_LogRecordImpl* result = nil;
	RHM_Comercial_LogRecordImpl* downloadState = nil;
    id<SUPStatementWrapper> preparedStatement = nil;
    id<SUPConnectionWrapper> connection = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
    
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
    	//@synchronized(connection)
    	{
        	@try
        	{
            	if (table == MainEntityTable)
            	{
                	preparedStatement = [connection prepareStatement:@"select \"e\",\"f\",\"g\",\"h\",\"i\",\"j\",\"l\",\"m\",\"n\",\"_pf\",\"_pc\",\"_rp\",\"_rf\",\"d\",\"_rc\",\"_ds\" from rhm_comercial_1_0_logrecordimpl where \"d\"=? order by \"_pf\""];
            	}
            	else
            	{
                	preparedStatement = [connection prepareStatement:@"select \"e\",\"f\",\"g\",\"h\",\"i\",\"j\",\"l\",\"m\",\"n\",\"_pf\",\"_pc\",\"_rp\",\"_rf\",\"d\",\"_rc\",\"_ds\" from rhm_comercial_1_0_logrecordimpl_os where \"d\"=? order by \"_pf\""];
            	}
            	[preparedStatement setLong:1:@"messageId":id_];
            	id<SUPResultSetWrapper> resultSet = [preparedStatement executeQuery];
            	while ([resultSet next])
            	{
            		if(result) [result release];
                	result = [[RHM_Comercial_LogRecordImpl alloc] init];
                	[result bind:resultSet];
                	if (table == OriginalStateEntityTable)
                	{
                    	result->_pending = false;
                    	result->_pendingChange = NotPending;
                	}
                	if (result.pending)
                	{
                    	break;
                	}
                	else
                	{
 	              		downloadState = [RHM_Comercial_LogRecordImpl getInstance];
                		[downloadState copyAll:result];
                	}
            	}
            	[resultSet close];      
        	}
        	@catch (SUPPersistenceException *spe)
        	{
            	@throw spe;
        	}
    	}
    }
    @catch (SUPPersistenceException *spe)
    {
        MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"find",[spe message]);
    }
    @finally
    {
    	if(preparedStatement) [preparedStatement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }
    if(result)
    {
    	if(result.pending)
    		result.downloadState = (SUPAbstractEntity*)downloadState;
  		//if(result != downloadState)
  		//	[downloadState release];
    }
    [result autorelease];
    return result;
}

+ (id<SUPSynchronizationGroup>)getSynchronizationGroup
{
	return [RHM_Comercial_RHM_ComercialDB getSyncGroupForName:@"LogRecordImpl"];
}

+ (SUPObjectList*)findWithQuery:(SUPQuery*)query
{
    id<SUPConnectionWrapper> connection = nil;
	if(query.selectItems != nil)
	{
		if(query.entityAlias == nil)
		{
			SUPEntityAlias *ea = [SUPEntityAlias getInstance];
			ea.alias = [[query.selectItems item:0] alias];
			ea.entity = @"LogRecordImpl";
			query.entityAlias = ea;
		}
		BOOL messageIdFound = NO;
		for(SUPSelectItem *si in query.selectItems)
		{
			if([si.attribute compare:@"messageId"] == 0)
				messageIdFound = YES;
		}
		if(!messageIdFound)
		{
			SUPSelectItem *si = [SUPSelectItem getInstance];
			si.attribute = @"messageId";
			si.alias = [query.entityAlias alias];
			[query.selectItems add:si];
		}
	}
id<SUPStatementWrapper> statement = nil;
id<SUPResultSetWrapper> resultSet = nil;
    {
        @try
        {    
            [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
            connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
            int32_t count = 0;
            RHM_Comercial_LogRecordImplList* list = [[RHM_Comercial_LogRecordImplList alloc] init];

            statement = [SUPStatementBuilder prepareQuery:connection:[RHM_Comercial_RHM_ComercialDB metaData]:[RHM_Comercial_LogRecordImpl metaData]:query];
            resultSet = [statement executeQuery];
            while ([resultSet next])
            {
                count++;   
                RHM_Comercial_LogRecordImpl* entity = [[RHM_Comercial_LogRecordImpl alloc] init];
                [entity bindWithQuery:resultSet:query];
                [list add:entity];
                [entity release];
            }
            [list autorelease];
            return list;
        }
        @catch (NSException *e)
        {
                    MBOLogPersistenceException(SUPCLIENTRT_PERSISTENCEEXCEPTIONMSG, @"findWithQuery",[NSString stringWithFormat:@"%@: %@",[e name],[e reason]]);
        }
        @finally
        {
            if(resultSet) [resultSet close];
            if(statement) [statement close];
            [connection releaseToPool];
            [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
        }
    }
    return nil;
}


- (id<SUPStatementWrapper>)getCreateStatement:(id<SUPConnectionWrapper>)connection forTable:(SUPEntityTable)table;
{
    id<SUPStatementWrapper> preparedStatement;
    if (table == MainEntityTable)
    {
        preparedStatement = [connection prepareStatement:@"insert into rhm_comercial_1_0_logrecordimpl (\"e\",\"f\",\"g\",\"h\",\"i\",\"j\",\"l\",\"m\",\"n\",\"_pf\",\"_pc\",\"_rp\",\"_rf\",\"d\",\"_rc\",\"_ds\") values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"];
    }
    else
    {
        preparedStatement = [connection prepareStatement:@"insert into rhm_comercial_1_0_logrecordimpl_os (\"e\",\"f\",\"g\",\"h\",\"i\",\"j\",\"l\",\"m\",\"n\",\"_pf\",\"_pc\",\"_rp\",\"_rf\",\"d\",\"_rc\",\"_ds\") values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"];
    }
    // Add updated values
    [preparedStatement setInt:1:@"e":self.level];
    [preparedStatement setInt:2:@"f":self.code];
    [preparedStatement setNullableString:3:@"g":self.eisCode];
    [preparedStatement setNullableString:4:@"h":self.message];
    [preparedStatement setNullableString:5:@"i":self.component];
    [preparedStatement setNullableString:6:@"j":self.entityKey];
    [preparedStatement setNullableString:7:@"l":self.operation];
    [preparedStatement setNullableString:8:@"m":self.requestId];
    [preparedStatement setNullableDateTime:9:@"n":self.timestamp];
    [preparedStatement setBoolean:10:@"_pf":((table == MainEntityTable) ? self->_pending : NO)];    		
    [preparedStatement setChar:11:@"_pc":((table == MainEntityTable) ? self->_pendingChange : 'N')];    		
    [preparedStatement setLong:12:@"_rp":((table == MainEntityTable) ? self->_replayPending : 0)];    		
    [preparedStatement setLong:13:@"_rf":((table == MainEntityTable) ? self->_replayFailure : 0)];    		
    [preparedStatement setLong:14:@"d":self.messageId];
    [preparedStatement setLong:15:@"_rc":((table == MainEntityTable) ? self.replayCounter : 0)];
    [preparedStatement setBoolean:16:@"_ds":self.disableSubmit];
	return preparedStatement;
}

- (id<SUPStatementWrapper>)getDeleteStatement:(id<SUPConnectionWrapper>)connection forTable:(SUPEntityTable)table;
{
    id<SUPStatementWrapper> preparedStatement;
    if (table == MainEntityTable)
    {
        preparedStatement = [connection prepareStatement:@"delete from rhm_comercial_1_0_logrecordimpl where \"_pf\"=? and \"d\"=?"];
    }
    else
    {
        preparedStatement = [connection prepareStatement:@"delete from rhm_comercial_1_0_logrecordimpl_os where \"_pf\"=? and \"d\"=?"];
    }
    // Fill in values for "where" clause
    [preparedStatement setBoolean:1:@"_pf":self->_pending];    		
    [preparedStatement setLong:2:@"d":self.messageId];
	return preparedStatement;
}

- (id<SUPStatementWrapper>)getUpdateStatement:(id<SUPConnectionWrapper>)connection forTable:(SUPEntityTable)table;
{
    id<SUPStatementWrapper> preparedStatement;
    if (table == MainEntityTable)
    {
    	preparedStatement = [connection prepareStatement:@"update rhm_comercial_1_0_logrecordimpl set \"e\"=?,\"f\"=?,\"g\"=?,\"h\"=?,\"i\"=?,\"j\"=?,\"l\"=?,\"m\"=?,\"n\"=?,\"_pc\"=?,\"_rp\"=?,\"_rf\"=?,\"_rc\"=?,\"_ds\"=? where \"_pf\"=? and \"d\"=?"];
    }
    else
    {
        preparedStatement = [connection prepareStatement:@"update rhm_comercial_1_0_logrecordimpl_os set \"e\"=?,\"f\"=?,\"g\"=?,\"h\"=?,\"i\"=?,\"j\"=?,\"l\"=?,\"m\"=?,\"n\"=?,\"_pc\"=?,\"_rp\"=?,\"_rf\"=?,\"_rc\"=?,\"_ds\"=? where \"_pf\"=? and \"d\"=?"];
    }
    // Add updated values
    int parameterIndex = 0;
    parameterIndex++;
    [preparedStatement setInt:parameterIndex:@"e":self.level];
    parameterIndex++;
    [preparedStatement setInt:parameterIndex:@"f":self.code];
    parameterIndex++;
    [preparedStatement setNullableString:parameterIndex:@"g":self.eisCode];
    parameterIndex++;
    [preparedStatement setNullableString:parameterIndex:@"h":self.message];
    parameterIndex++;
    [preparedStatement setNullableString:parameterIndex:@"i":self.component];
    parameterIndex++;
    [preparedStatement setNullableString:parameterIndex:@"j":self.entityKey];
    parameterIndex++;
    [preparedStatement setNullableString:parameterIndex:@"l":self.operation];
    parameterIndex++;
    [preparedStatement setNullableString:parameterIndex:@"m":self.requestId];
    parameterIndex++;
    [preparedStatement setNullableDateTime:parameterIndex:@"n":self.timestamp];
    parameterIndex++;
    [preparedStatement setChar:parameterIndex:@"_pc":self->_pendingChange];
    parameterIndex++;
    [preparedStatement setLong:parameterIndex:@"_rp":self->_replayPending];
    parameterIndex++;
    [preparedStatement setLong:parameterIndex:@"_rf":self->_replayFailure];
    parameterIndex++;
    [preparedStatement setLong:parameterIndex:@"_rc":self.replayCounter];
    parameterIndex++;
    [preparedStatement setBoolean:parameterIndex:@"_ds":self.disableSubmit];
    // Fill in values for "where" clause
    parameterIndex++;
    [preparedStatement setBoolean:parameterIndex:@"_pf":self->_pending];
    parameterIndex++;
    [preparedStatement setLong:parameterIndex:@"d":self.messageId];
	return preparedStatement;
}

- (int64_t)_pk
{
	return [self id];
}

- (int64_t)id
{
    return self.messageId;
}

- (NSString*)keyToString
{
	return [NSString stringWithFormat:@"%d",[self id]];
}

+ (void)importData:(RHM_Comercial_LogRecordImpl*)serverEntity:(SUPJsonObject*)jsonObject
{
	NSAutoreleasePool *importDataPool = [[NSAutoreleasePool alloc] init];
	RHM_Comercial_LogRecordImpl* serverEntity2 = [RHM_Comercial_LogRecordImpl getInstance];
    [serverEntity2 copyAll:serverEntity];
    
    if([serverEntity2 database].callbackHandler)
		[[serverEntity2 database].callbackHandler beforeImport:serverEntity2];
    if([RHM_Comercial_LogRecordImpl callbackHandler])
		[[RHM_Comercial_LogRecordImpl callbackHandler] beforeImport:serverEntity2];
	
    [serverEntity retain];
    SUPBoolean upsert = !(serverEntity.isDeleted)  && (!serverEntity.isNew) && (!serverEntity.isDirty);
    SUPBoolean create = serverEntity.isNew;
    SUPBoolean update = serverEntity.isDirty;
    SUPBoolean delete = serverEntity.isDeleted;
    
    serverEntity->_pendingChange = NotPending;
    serverEntity.replayPending = 0;
    if(upsert || create)
    {
    	@try
    	{
    		[serverEntity createPending:NO];
    	}
    	@catch(NSException *e)
    	{
    		serverEntity.isDirty = YES;
    		update = YES;
    	}
    } else if(delete)
    {
    	BOOL isCreated = NO;
    	@try
    	{
    		// check to see if server is trying to delete a newly created row
    		[serverEntity createPending:NO];
    		isCreated = YES;
    	}
    	@catch(NSException *e)
    	{
    	}
        [serverEntity deletePending:NO];
        serverEntity->_isDeleted = YES;
        serverEntity.pending = YES;
        serverEntity.pendingChange = PendingDelete;
        if(isCreated) 
        {
            RHM_Comercial_LogRecordImpl *clientEntity = [RHM_Comercial_LogRecordImpl find:[serverEntity _pk]];
            if(clientEntity != nil && clientEntity.pending)
            {
				[serverEntity refresh];
				serverEntity->_isDeleted = YES;
				serverEntity.replayCounter = 0;
				serverEntity.replayFailure = serverEntity.replayCounter;
            }
			serverEntity->_isNew = YES;
        }
    } 
	if(update)
    {
    	RHM_Comercial_LogRecordImpl *clientEntity = [RHM_Comercial_LogRecordImpl find:[serverEntity _pk]];
    	if(clientEntity.pending)
    		clientEntity = (RHM_Comercial_LogRecordImpl*)clientEntity.downloadState;
        @try 
        {
            [serverEntity merge:clientEntity withJson:jsonObject];
        } @catch(SUPJsonException *je)
        {
            NSException *e = [[NSException alloc] initWithName:@"SUPJsonException" reason:[je message] userInfo:nil];
            @throw e;
        }
        serverEntity.pending = NO;
        [serverEntity updatePending:NO];
        serverEntity.isDirty = YES;
        serverEntity.pending = YES;
        serverEntity.pendingChange = PendingUpdate;
    }
    if(create)
    {
        serverEntity->_isNew = YES;
        serverEntity.pending = YES;
        serverEntity.pendingChange = PendingCreate;
    }
    if([serverEntity database].callbackHandler)
		[[serverEntity database].callbackHandler onImport:serverEntity];
    if([RHM_Comercial_LogRecordImpl callbackHandler])
		[[RHM_Comercial_LogRecordImpl callbackHandler] onImport:serverEntity];

    [serverEntity release];
   
#ifdef LOGRECORD_ON_IMPORT
	[serverEntity createLogRecord:[SUPLogLevel info] withMessage:@"data import"];
#endif
	[importDataPool drain];
}

+ (RHM_Comercial_LogRecordImpl*)load:(int64_t)id
{
	RHM_Comercial_LogRecordImpl* entity = [self find:id inTable:MainEntityTable];
	//RHM_Comercial_LogRecordImpl* entity = [self find:id];
    if (entity == nil)
    {
		@throw [SUPObjectNotFoundException withMessage:@"-load: in RHM_Comercial_LogRecordImpl: entity not found in database"];
    }
    return entity;
}

static SUPEntityMetaData* RHM_Comercial_LogRecordImpl_META_DATA;
static BOOL _valid_ = NO;

+ (SUPEntityMetaData*)metaData
{
    if (! (_valid_))
    {
       RHM_Comercial_LogRecordImpl_META_DATA = [SUPEntityMetaData getInstance];
       RHM_Comercial_LogRecordImpl_META_DATA.id = _ENTITY_NUMBER_FOR_RHM_Comercial_LogRecordImpl_;
       RHM_Comercial_LogRecordImpl_META_DATA.name = @"LogRecordImpl";
       [RHM_Comercial_LogRecordImpl_META_DATA setClass:[RHM_Comercial_LogRecordImpl class]];

	   RHM_Comercial_LogRecordImpl_META_DATA.isClientOnly = NO;

       // Handle attributes
       
       	SUPObjectList *attributes = [SUPObjectList getInstance];
		SUPAttributeMetaData_DC* a_level = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:1:(SUPString)@"level":[SUPDataType forName:@"int"]];
		[a_level setColumn:@"\"e\""];
		[a_level setMaxLength:-1];
		[a_level setPrecision:0];
		[a_level setScale:0];
		[a_level setIsKey:NO];
		SUPAttributeMetaData_DC* a_code = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:2:(SUPString)@"code":[SUPDataType forName:@"int"]];
		[a_code setColumn:@"\"f\""];
		[a_code setMaxLength:-1];
		[a_code setPrecision:0];
		[a_code setScale:0];
		[a_code setIsKey:NO];
		SUPAttributeMetaData_DC* a_eisCode = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:3:(SUPString)@"eisCode":[SUPDataType forName:@"string?"]];
		[a_eisCode setColumn:@"\"g\""];
		[a_eisCode setMaxLength:10];
		[a_eisCode setPrecision:0];
		[a_eisCode setScale:0];
		[a_eisCode setIsKey:NO];
		SUPAttributeMetaData_DC* a_message = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:4:(SUPString)@"message":[SUPDataType forName:@"string?"]];
		[a_message setColumn:@"\"h\""];
		[a_message setMaxLength:8000];
		[a_message setPrecision:0];
		[a_message setScale:0];
		[a_message setIsKey:NO];
		SUPAttributeMetaData_DC* a_component = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:5:(SUPString)@"component":[SUPDataType forName:@"string?"]];
		[a_component setColumn:@"\"i\""];
		[a_component setMaxLength:100];
		[a_component setPrecision:0];
		[a_component setScale:0];
		[a_component setIsKey:NO];
		SUPAttributeMetaData_DC* a_entityKey = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:6:(SUPString)@"entityKey":[SUPDataType forName:@"string?"]];
		[a_entityKey setColumn:@"\"j\""];
		[a_entityKey setMaxLength:256];
		[a_entityKey setPrecision:0];
		[a_entityKey setScale:0];
		[a_entityKey setIsKey:NO];
		SUPAttributeMetaData_DC* a_operation = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:7:(SUPString)@"operation":[SUPDataType forName:@"string?"]];
		[a_operation setColumn:@"\"l\""];
		[a_operation setMaxLength:100];
		[a_operation setPrecision:0];
		[a_operation setScale:0];
		[a_operation setIsKey:NO];
		SUPAttributeMetaData_DC* a_requestId = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:8:(SUPString)@"requestId":[SUPDataType forName:@"string?"]];
		[a_requestId setColumn:@"\"m\""];
		[a_requestId setMaxLength:100];
		[a_requestId setPrecision:0];
		[a_requestId setScale:0];
		[a_requestId setIsKey:NO];
		SUPAttributeMetaData_DC* a_timestamp = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:9:(SUPString)@"timestamp":[SUPDataType forName:@"dateTime?"]];
		[a_timestamp setColumn:@"\"n\""];
		[a_timestamp setMaxLength:-1];
		[a_timestamp setPrecision:0];
		[a_timestamp setScale:0];
		[a_timestamp setIsKey:NO];
		SUPAttributeMetaData_DC* a_pending = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:10:(SUPString)@"pending":[SUPDataType forName:@"boolean"]];
		[a_pending setColumn:@"\"_pf\""];
		[a_pending setMaxLength:-1];
		[a_pending setPrecision:0];
		[a_pending setScale:0];
		[a_pending setIsKey:NO];
		SUPAttributeMetaData_DC* a_pendingChange = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:11:(SUPString)@"pendingChange":[SUPDataType forName:@"char"]];
		[a_pendingChange setColumn:@"\"_pc\""];
		[a_pendingChange setMaxLength:1];
		[a_pendingChange setPrecision:0];
		[a_pendingChange setScale:0];
		[a_pendingChange setIsKey:NO];
		SUPAttributeMetaData_DC* a_replayPending = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:12:(SUPString)@"replayPending":[SUPDataType forName:@"long"]];
		[a_replayPending setColumn:@"\"_rp\""];
		[a_replayPending setMaxLength:-1];
		[a_replayPending setPrecision:0];
		[a_replayPending setScale:0];
		[a_replayPending setIsKey:NO];
		SUPAttributeMetaData_DC* a_replayFailure = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:13:(SUPString)@"replayFailure":[SUPDataType forName:@"long"]];
		[a_replayFailure setColumn:@"\"_rf\""];
		[a_replayFailure setMaxLength:-1];
		[a_replayFailure setPrecision:0];
		[a_replayFailure setScale:0];
		[a_replayFailure setIsKey:NO];
		SUPAttributeMetaData_DC* a_messageId = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:14:(SUPString)@"messageId":[SUPDataType forName:@"long"]];
		[a_messageId setColumn:@"\"d\""];
		[a_messageId setMaxLength:-1];
		[a_messageId setPrecision:0];
		[a_messageId setScale:0];
		[a_messageId setIsKey:YES];
		SUPAttributeMetaData_DC* a_replayCounter = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:15:(SUPString)@"replayCounter":[SUPDataType forName:@"long"]];
		[a_replayCounter setColumn:@"\"_rc\""];
		[a_replayCounter setMaxLength:-1];
		[a_replayCounter setPrecision:0];
		[a_replayCounter setScale:0];
		[a_replayCounter setIsKey:NO];
		SUPAttributeMetaData_DC* a_disableSubmit = [RHM_Comercial_RHM_ComercialDB createAttributeMetaData:16:(SUPString)@"disableSubmit":[SUPDataType forName:@"boolean"]];
		[a_disableSubmit setColumn:@"\"_ds\""];
		[a_disableSubmit setMaxLength:-1];
		[a_disableSubmit setPrecision:0];
		[a_disableSubmit setScale:0];
		[a_disableSubmit setIsKey:NO];
 		
 		[attributes addThis:a_level];
 		[attributes addThis:a_code];
 		[attributes addThis:a_eisCode];
 		[attributes addThis:a_message];
 		[attributes addThis:a_component];
 		[attributes addThis:a_entityKey];
 		[attributes addThis:a_operation];
 		[attributes addThis:a_requestId];
 		[attributes addThis:a_timestamp];
 		[attributes addThis:a_pending];
 		[attributes addThis:a_pendingChange];
 		[attributes addThis:a_replayPending];
 		[attributes addThis:a_replayFailure];
 		[attributes addThis:a_messageId];
 		[attributes addThis:a_replayCounter];
 		[attributes addThis:a_disableSubmit];
 		RHM_Comercial_LogRecordImpl_META_DATA.attributes = attributes;
 		
 		SUPAttributeMap * attributeMap = [SUPAttributeMap getInstance];
    	[attributeMap setAttributes:attributes];
    	RHM_Comercial_LogRecordImpl_META_DATA.attributeMap = [attributeMap finishInit];
 
 		// Handle operations
 		SUPOperationMetaData* o_create_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:1:(SUPString)@"create":[SUPDataType forName:@"void"]:true];
		[o_create_0 setIsStatic:NO];
		[o_create_0 setIsCreate:YES];
		[o_create_0 setIsUpdate:NO];
		[o_create_0 setIsDelete:NO]; 		
 		[o_create_0 finishInit];
 		SUPOperationMetaData* o_update_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:2:(SUPString)@"update":[SUPDataType forName:@"void"]:true];
		[o_update_0 setIsStatic:NO];
		[o_update_0 setIsCreate:NO];
		[o_update_0 setIsUpdate:YES];
		[o_update_0 setIsDelete:NO]; 		
 		[o_update_0 finishInit];
 		SUPOperationMetaData* o_delete_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:3:(SUPString)@"delete":[SUPDataType forName:@"void"]:true];
		[o_delete_0 setIsStatic:NO];
		[o_delete_0 setIsCreate:NO];
		[o_delete_0 setIsUpdate:NO];
		[o_delete_0 setIsDelete:YES]; 		
 		[o_delete_0 finishInit];
 		SUPOperationMetaData* o_getPendingObjects_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:4:(SUPString)@"getPendingObjects":[SUPDataType forName:@"LogRecordImpl*"]:true];
		[o_getPendingObjects_0 setIsStatic:YES];
		[o_getPendingObjects_0 setIsCreate:NO];
		[o_getPendingObjects_0 setIsUpdate:NO];
		[o_getPendingObjects_0 setIsDelete:NO]; 		
 		[o_getPendingObjects_0 finishInit];
 		SUPOperationMetaData* o_getPendingObjects_1 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:5:(SUPString)@"getPendingObjects":[SUPDataType forName:@"LogRecordImpl*"]:true];
  		{
 			SUPObjectList *parameters_list = nil;
 			SUPParameterMetaData* p_getPendingObjects_pendingChange = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:1:(SUPString)@"pendingChange":[SUPDataType forName:@"char"]];
 			parameters_list = [SUPObjectList listWithCapacity:1];
 			[parameters_list addThis:p_getPendingObjects_pendingChange];
 			o_getPendingObjects_1.parameters = parameters_list;

 		}
		[o_getPendingObjects_1 setIsStatic:YES];
		[o_getPendingObjects_1 setIsCreate:NO];
		[o_getPendingObjects_1 setIsUpdate:NO];
		[o_getPendingObjects_1 setIsDelete:NO]; 		
 		[o_getPendingObjects_1 finishInit];
 		SUPOperationMetaData* o_getReplayPendingObjects_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:6:(SUPString)@"getReplayPendingObjects":[SUPDataType forName:@"LogRecordImpl*"]:true];
		[o_getReplayPendingObjects_0 setIsStatic:YES];
		[o_getReplayPendingObjects_0 setIsCreate:NO];
		[o_getReplayPendingObjects_0 setIsUpdate:NO];
		[o_getReplayPendingObjects_0 setIsDelete:NO]; 		
 		[o_getReplayPendingObjects_0 finishInit];
 		SUPOperationMetaData* o_refresh_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:7:(SUPString)@"refresh":[SUPDataType forName:@"void"]:true];
		[o_refresh_0 setIsStatic:NO];
		[o_refresh_0 setIsCreate:NO];
		[o_refresh_0 setIsUpdate:NO];
		[o_refresh_0 setIsDelete:NO]; 		
 		[o_refresh_0 finishInit];
 		SUPOperationMetaData* o__pk_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:8:(SUPString)@"_pk":[SUPDataType forName:@"long?"]:true];
		[o__pk_0 setIsStatic:NO];
		[o__pk_0 setIsCreate:NO];
		[o__pk_0 setIsUpdate:NO];
		[o__pk_0 setIsDelete:NO]; 		
 		[o__pk_0 finishInit];
 		SUPOperationMetaData* o_submitPending_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:9:(SUPString)@"submitPending":[SUPDataType forName:@"void"]:true];
		[o_submitPending_0 setIsStatic:NO];
		[o_submitPending_0 setIsCreate:NO];
		[o_submitPending_0 setIsUpdate:NO];
		[o_submitPending_0 setIsDelete:NO]; 		
 		[o_submitPending_0 finishInit];
 		SUPOperationMetaData* o_cancelPending_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:10:(SUPString)@"cancelPending":[SUPDataType forName:@"void"]:true];
		[o_cancelPending_0 setIsStatic:NO];
		[o_cancelPending_0 setIsCreate:NO];
		[o_cancelPending_0 setIsUpdate:NO];
		[o_cancelPending_0 setIsDelete:NO]; 		
 		[o_cancelPending_0 finishInit];
 		SUPOperationMetaData* o_submitPendingOperations_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:11:(SUPString)@"submitPendingOperations":[SUPDataType forName:@"void"]:true];
		[o_submitPendingOperations_0 setIsStatic:YES];
		[o_submitPendingOperations_0 setIsCreate:NO];
		[o_submitPendingOperations_0 setIsUpdate:NO];
		[o_submitPendingOperations_0 setIsDelete:NO]; 		
 		[o_submitPendingOperations_0 finishInit];
 		SUPOperationMetaData* o_cancelPendingOperations_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:12:(SUPString)@"cancelPendingOperations":[SUPDataType forName:@"void"]:true];
		[o_cancelPendingOperations_0 setIsStatic:YES];
		[o_cancelPendingOperations_0 setIsCreate:NO];
		[o_cancelPendingOperations_0 setIsUpdate:NO];
		[o_cancelPendingOperations_0 setIsDelete:NO]; 		
 		[o_cancelPendingOperations_0 finishInit];
 		SUPOperationMetaData* o_save_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:13:(SUPString)@"save":[SUPDataType forName:@"void"]:true];
		[o_save_0 setIsStatic:NO];
		[o_save_0 setIsCreate:NO];
		[o_save_0 setIsUpdate:NO];
		[o_save_0 setIsDelete:NO]; 		
 		[o_save_0 finishInit];
 		SUPOperationMetaData* o_findWithQuery_1 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:14:(SUPString)@"findWithQuery":[SUPDataType forName:@"LogRecordImpl*"]:true];
  		{
 			SUPObjectList *parameters_list = nil;
 			SUPParameterMetaData* p_findWithQuery_query = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:1:(SUPString)@"query":[SUPDataType forName:@"com.sybase.persistence.Query"]];
 			parameters_list = [SUPObjectList listWithCapacity:1];
 			[parameters_list addThis:p_findWithQuery_query];
 			o_findWithQuery_1.parameters = parameters_list;

 		}
		[o_findWithQuery_1 setIsStatic:YES];
		[o_findWithQuery_1 setIsCreate:NO];
		[o_findWithQuery_1 setIsUpdate:NO];
		[o_findWithQuery_1 setIsDelete:NO]; 		
 		[o_findWithQuery_1 finishInit];
 		SUPOperationMetaData* o_getSize_1 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:15:(SUPString)@"getSize":[SUPDataType forName:@"int"]:true];
  		{
 			SUPObjectList *parameters_list = nil;
 			SUPParameterMetaData* p_getSize_query = [RHM_Comercial_RHM_ComercialDB createParameterMetaData:1:(SUPString)@"query":[SUPDataType forName:@"com.sybase.persistence.Query"]];
 			parameters_list = [SUPObjectList listWithCapacity:1];
 			[parameters_list addThis:p_getSize_query];
 			o_getSize_1.parameters = parameters_list;

 		}
		[o_getSize_1 setIsStatic:YES];
		[o_getSize_1 setIsCreate:NO];
		[o_getSize_1 setIsUpdate:NO];
		[o_getSize_1 setIsDelete:NO]; 		
 		[o_getSize_1 finishInit];
 		SUPOperationMetaData* o_countReplayPendingObjects_0 = [RHM_Comercial_RHM_ComercialDB createOperationMetaData:16:(SUPString)@"countReplayPendingObjects":[SUPDataType forName:@"int"]:true];
		[o_countReplayPendingObjects_0 setIsStatic:YES];
		[o_countReplayPendingObjects_0 setIsCreate:NO];
		[o_countReplayPendingObjects_0 setIsUpdate:NO];
		[o_countReplayPendingObjects_0 setIsDelete:NO]; 		
 		[o_countReplayPendingObjects_0 finishInit];
 
  		SUPObjectList *operations = [SUPObjectList listWithCapacity:16];
 		[operations addThis:o_create_0];
 		[operations addThis:o_update_0];
 		[operations addThis:o_delete_0];
 		[operations addThis:o_getPendingObjects_0];
 		[operations addThis:o_getPendingObjects_1];
 		[operations addThis:o_getReplayPendingObjects_0];
 		[operations addThis:o_refresh_0];
 		[operations addThis:o__pk_0];
 		[operations addThis:o_submitPending_0];
 		[operations addThis:o_cancelPending_0];
 		[operations addThis:o_submitPendingOperations_0];
 		[operations addThis:o_cancelPendingOperations_0];
 		[operations addThis:o_save_0];
 		[operations addThis:o_findWithQuery_1];
 		[operations addThis:o_getSize_1];
 		[operations addThis:o_countReplayPendingObjects_0];
 		RHM_Comercial_LogRecordImpl_META_DATA.operations = operations;
 		
		SUPOperationMap *operationMap = [SUPOperationMap getInstance];
		[operationMap setOperations:operations];
		RHM_Comercial_LogRecordImpl_META_DATA.operationMap = [operationMap finishInit];
		
		RHM_Comercial_LogRecordImpl_META_DATA.table = @"\"rhm_comercial_1_0_logrecordimpl\"";

 		[RHM_Comercial_LogRecordImpl_META_DATA retain];
     	_valid_ = YES;

	}
	return RHM_Comercial_LogRecordImpl_META_DATA;
}

- (void)merge:(RHM_Comercial_LogRecordImpl*)entity withJson:(SUPJsonObject*)json
{
	[super merge:entity withJson:json];
    if(![json containsKey:@"level"] )
    {
    	self.level = entity.level;
    }
    else if(![json getInt:@"level"])
    {
    	self.level = entity.level;
    }
    if(![json containsKey:@"code"] )
    {
    	self.code = entity.code;
    }
    else if(![json getInt:@"code"])
    {
    	self.code = entity.code;
    }
    if(![json containsKey:@"eisCode"] )
    {
    	self.eisCode = entity.eisCode;
    }
    else if(![json getNullableString:@"eisCode"])
    {
    	self.eisCode = entity.eisCode;
    }
    if(![json containsKey:@"message"] )
    {
    	self.message = entity.message;
    }
    else if(![json getNullableString:@"message"])
    {
    	self.message = entity.message;
    }
    if(![json containsKey:@"component"] )
    {
    	self.component = entity.component;
    }
    else if(![json getNullableString:@"component"])
    {
    	self.component = entity.component;
    }
    if(![json containsKey:@"entityKey"] )
    {
    	self.entityKey = entity.entityKey;
    }
    else if(![json getNullableString:@"entityKey"])
    {
    	self.entityKey = entity.entityKey;
    }
    if(![json containsKey:@"operation"] )
    {
    	self.operation = entity.operation;
    }
    else if(![json getNullableString:@"operation"])
    {
    	self.operation = entity.operation;
    }
    if(![json containsKey:@"requestId"] )
    {
    	self.requestId = entity.requestId;
    }
    else if(![json getNullableString:@"requestId"])
    {
    	self.requestId = entity.requestId;
    }
    if(![json containsKey:@"timestamp"] )
    {
    	self.timestamp = entity.timestamp;
    }
    else if(![json getNullableDateTime:@"timestamp"])
    {
    	self.timestamp = entity.timestamp;
    }
    if(![json containsKey:@"messageId"] )
    {
    	self.messageId = entity.messageId;
    }
    else if(![json getLong:@"messageId"])
    {
    	self.messageId = entity.messageId;
    }
    if(![json containsKey:@"disableSubmit"] )
    {
    	self.disableSubmit = entity.disableSubmit;
    }
    else if(![json getBoolean:@"disableSubmit"])
    {
    	self.disableSubmit = entity.disableSubmit;
    }
}

+ (RHM_Comercial_LogRecordImpl*)getInstance
{
    RHM_Comercial_LogRecordImpl* me = [[RHM_Comercial_LogRecordImpl alloc] init];
    [me autorelease];
    return me;
}

- (SUPObjectList*)getLogRecords
{
    SUPQuery *query = [SUPQuery getInstance];
    [query from:@"LogRecordImpl":@"a"];
    query.testCriteria = (SUPTestCriteria*)[[SUPAttributeTest match:@"component":@"LogRecordImpl"] and:[SUPAttributeTest match:@"entityKey":[self keyToString]]];
    [query orderBy:@"requestId":[SUPSortOrder DESCENDING]];

    RHM_Comercial_LogRecordImplList* list = [RHM_Comercial_LogRecordImpl findWithQuery:query];
    return (SUPObjectList*)list;
}

- (id<SUPLogRecord>)createLogRecord:(int32_t)level withMessage:(NSString*)message
{
    {
        RHM_Comercial_LogRecordImpl *log = [[RHM_Comercial_LogRecordImpl alloc] init];
        //log.level = [NSString stringWithFormat:@"%ld",[SUPLogLevel fromString:level]];
        log.level = level;
        log.message = message;
        log.messageId = [RHM_Comercial_KeyGenerator generateId];
        log.requestId = [NSString stringWithFormat:@"%ld",log.messageId];
        NSDate *timestamp = [NSDate dateWithTimeIntervalSinceNow:0];
        log.timestamp = timestamp;
        log.code = CLIENT_ENTITY_CREATED_LOGRECORD_CODE;
        log.component = @"LogRecordImpl";
        log.entityKey = [self keyToString];
        [log save];
        [log autorelease];
        return log;
    }
}

- (void)setAllAttributesFrom:(RHM_Comercial_LogRecordImpl*)other
{
	// Child lists are set to nil, to prevent infinite recursion
	// when this method is used inside the bind: method
    	[self setLevel:other.level];
    	[self setCode:other.code];
    	[self setEisCode:other.eisCode];
    	[self setMessage:other.message];
    	[self setComponent:other.component];
    	[self setEntityKey:other.entityKey];
    	[self setOperation:other.operation];
    	[self setRequestId:other.requestId];
    	[self setTimestamp:other.timestamp];
    	self->_pending = other->_pending;
    	self->_pendingChange = other->_pendingChange;
    	self->_replayPending = other->_replayPending;
    	self->_replayFailure = other->_replayFailure;
    	[self setMessageId:other.messageId];
    	self->_replayCounter = other->_replayCounter;
    	[self setDisableSubmit:other.disableSubmit];
}

+ (NSObject<SUPCallbackHandler>*)callbackHandler
{
	return _callbackHandler;
}

+ (void)registerCallbackHandler:(NSObject<SUPCallbackHandler>*)newCallbackHandler
{
	if(newCallbackHandler != _callbackHandler)
	{
		[_callbackHandler release];
		_callbackHandler = [newCallbackHandler retain];
	}
}

- (void)refresh
{
    if (!self.isNew)
    {
        RHM_Comercial_LogRecordImpl* entity = [RHM_Comercial_LogRecordImpl load:[self id]];
        [self copyAll:entity];
		if(self.pending && self.pendingChange == PendingCreate)
		{
			self.originalState = self;
		}
		else
		{
			self.originalState = nil;
			self->_originalStateValid = NO;
		}
        _isNew = NO;
        _isDirty = NO;
    }
}



+ (void)replayAccepted:(SUPJsonObject*)headers withContent:(SUPJsonArray*)content
{
	for (id item in content)
    {
        SUPJsonObject* jsonObject = (SUPJsonObject*)(item);
		int64_t key;
		if ([jsonObject containsKey:@"messageId"]) 
		{
			key = [jsonObject getLong:@"messageId"];
		}
		else
		{
		    key = [jsonObject getLong:@"id"];
		}
        if ([headers containsKey:@"log"]) 
        {
            for(SUPJsonObject *o in [headers getArray:@"log"])
			{
				if(![o containsKey:@"entityKey"])
				{
					RHM_Comercial_LogRecordImpl* entity = [[RHM_Comercial_LogRecordImpl alloc] init];
					entity.messageId = key;
					[o setString:@"entityKey":[entity keyToString]];
					[entity release];
				}
				[RHM_Comercial_RHM_ComercialDB writeLogFromHeader:o:@"LogRecordImpl":@"replay"];
			}
        }

        RHM_Comercial_LogRecordImpl* clientEntity = [RHM_Comercial_LogRecordImpl find:key];
        if( (clientEntity != nil) && (clientEntity.pending) )
        {
            SUPLong server_id = [SUPBindUtil parseLong:[headers getString:@"id"]];
            SUPLong client_rc = [clientEntity replayPending];
            if(client_rc == server_id)
            {
            	// Server has already sent updated records, so delete the pending ones
                SUPChar pendingChange = clientEntity.pendingChange;
                [clientEntity cancelReplayPending:(SUPAbstractEntity*)clientEntity];
				clientEntity->_originalState = nil;
				clientEntity->_originalStateValid = NO;
				clientEntity.pending = YES;
				clientEntity.pendingChange = pendingChange;
				clientEntity->_isNew = (pendingChange == PendingCreate);
				clientEntity->_isDirty = (pendingChange == PendingUpdate);
				clientEntity->_isDeleted = (pendingChange == PendingDelete);
				if([RHM_Comercial_LogRecordImpl callbackHandler])
	        		[[RHM_Comercial_LogRecordImpl callbackHandler] onReplaySuccess:clientEntity];       
		        if([RHM_Comercial_RHM_ComercialDB callbackHandler])
		        	[[RHM_Comercial_RHM_ComercialDB callbackHandler] onReplaySuccess:clientEntity];
            }
        }
        
    }
}



+ (void)replayRejected:(SUPJsonObject*)headers withContent:(SUPJsonArray*)content
{
    for (id item in content)
    {
        SUPJsonObject* jsonObject = (SUPJsonObject*)(item);
		int64_t key;
		if ([jsonObject containsKey:@"messageId"]) 
		{
			key = [jsonObject getLong:@"messageId"];
		}
		else
		{
		    key = [jsonObject getLong:@"id"];
		}        
        if ([headers containsKey:@"log"]) 
        {
            for(SUPJsonObject *o in [headers getArray:@"log"])
			{
				if(![o containsKey:@"entityKey"])
				{
					RHM_Comercial_LogRecordImpl* entity = [[RHM_Comercial_LogRecordImpl alloc] init];
					entity.messageId = key;
					[o setString:@"entityKey":[entity keyToString]];
					[entity release];
				}
				[RHM_Comercial_RHM_ComercialDB writeLogFromHeader:o:@"LogRecordImpl":@"replay"];
			}
        }
        RHM_Comercial_LogRecordImpl* clientEntity = [RHM_Comercial_LogRecordImpl find:key]; 
        [clientEntity retain];
        if(clientEntity != nil)
        {
            SUPLong server_id = [SUPBindUtil parseLong:[headers getString:@"id"]];
            SUPLong client_rc = [clientEntity replayCounter];
            if(client_rc == server_id)
            {
	        	RHM_Comercial_LogRecordImpl* originalState = (RHM_Comercial_LogRecordImpl*)clientEntity.originalState;
	        	SUPChar pendingChange = clientEntity.pendingChange;
            	[clientEntity replayRejected_childcascade];
            	clientEntity.originalState = originalState;
            	clientEntity.pending = YES;
            	clientEntity.pendingChange = pendingChange;
				clientEntity->_isNew = (pendingChange == PendingCreate);
				clientEntity->_isDirty = (pendingChange == PendingUpdate);
				clientEntity->_isDeleted = (pendingChange == PendingDelete);
			    if([RHM_Comercial_LogRecordImpl callbackHandler])
			    	[[RHM_Comercial_LogRecordImpl callbackHandler] onReplayFailure:clientEntity];
		        if([RHM_Comercial_RHM_ComercialDB callbackHandler])
		        	[[RHM_Comercial_RHM_ComercialDB callbackHandler] onReplayFailure:clientEntity];
            }
        }
        [clientEntity autorelease];
     }
}



-(void)submitPending
{
	[self submitPending1:YES];
}

-(void)submitPendingNoRefresh
{
	[self submitPending1:NO];
}

-(void)submitPending1:(BOOL)doRefresh
{
    id<SUPConnectionWrapper> connection = nil;
    SUPLocalTransaction* transaction = nil;
    BOOL success = NO;
    SUPJsonMessage* message = nil;
    
    [RHM_Comercial_RHM_ComercialDB checkIfSubscribed];
    //if(_disableSubmit)
    //    return;
    //if(_replayPending == _replayCounter) // already submitted
    //	return;
    @try
    {
        message = [[SUPJsonMessage alloc] init];
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];    
        connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
        transaction = ([connection inTransaction] ? nil : [RHM_Comercial_RHM_ComercialDB beginTransaction]);
    	if(doRefresh)
	        [self refresh];
        if (self.pending && !self.disableSubmit && (self.replayCounter > self.replayPending))
        {
            SUPJsonObject* headers = [message headers];
            [headers setString:@"pkg":@"RHM_Comercial:1.0"];
            [headers setString:@"mbo":@"LogRecordImpl"];
            [headers setString:@"method":@"replay"];
            [headers setString:@"id":[SUPStringUtil toString_long:self.replayCounter]];

			
            [message setContent:[self json:2]];
            
            self.replayFailure = 0;
            self.replayCounter = 0;
            self.replayPending = self.replayCounter;
            [self updatePending:YES];
        }
        if (transaction != nil)
        {
            [transaction commit];
        }
        success = YES;
    }
    @catch (NSException* e)
    {
        if (transaction != nil)
        {
            [transaction rollback];
        }
        success = NO;
        @throw e;
    }
    @finally
    {
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
        if(success)
            [RHM_Comercial_RHM_ComercialDB replay:@"LogRecordImpl" withId:self.replayCounter withContent:[message content]];
        [message release];
    }
}

- (void)submitPending_save_childcascade:(SUPAbstractEntity*)parent
{
	if([self pending])
	{
		self->_replayCounter = parent->_replayCounter;
		[self updatePending:YES];
    }
}

- (void)submitPending_update_childcascade:(SUPAbstractEntity*)parent
{
    if ([self pending])
    {
        //BOOL isCreate = [self isCreated];
	    self.replayFailure = 0;
	    self.replayPending = self.replayCounter;
	    [self updatePending:YES];
        //if(!isCreate)
        //    [self updateOriginalState];
    }        

}

 
+ (void)submitPendingOperations
{
	[super submitPendingOperations];
}

+ (void)cancelPendingOperations
{
	[super cancelPendingOperations];
}

- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	LogRecordImpl = \n\
	    level = %i,\n\
	    code = %i,\n\
	    eisCode = %@,\n\
	    message = %@,\n\
	    component = %@,\n\
	    entityKey = %@,\n\
	    operation = %@,\n\
	    requestId = %@,\n\
	    timestamp = %@,\n\
	    pending = %i,\n\
	    pendingChange = %c,\n\
	    replayPending = %qi,\n\
	    replayFailure = %qi,\n\
	    messageId = %qi,\n\
	    replayCounter = %qi,\n\
	    disableSubmit = %i,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.level
    	,self.code
    	,self.eisCode
    	,self.message
    	,self.component
    	,self.entityKey
    	,self.operation
    	,self.requestId
    	,self.timestamp
    	,self->_pending
    	,self->_pendingChange
    	,self->_replayPending
    	,self->_replayFailure
    	,self.messageId
    	,self->_replayCounter
    	,self.disableSubmit
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}

- (void)save
{
    if (self->_isNew)
    {
        [self create];
    }
    else if (self->_isDirty)
    {
        [self update];
    }
}


- (void)createPending:(BOOL)isPending
{
   	id<SUPConnectionWrapper> connection = nil;
    id<SUPStatementWrapper> statement = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
    	self->_pending = isPending;
    	if(!isPending)
    	{
    		self->_replayPending = 0;
    		self->_replayFailure = 0;
    	}
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
    	statement = [self getCreateStatement:connection forTable:MainEntityTable];
		[statement executeInsert];
		self->_isNew = NO;
		self->_isDirty = NO;
		self->_isDeleted = NO;
		if (isPending)
		{
			RHM_Comercial_LogRecordImpl* originalEntity = (RHM_Comercial_LogRecordImpl*)[self originalState];
			if (originalEntity != nil)
			{
				originalEntity.pending = NO;
				id<SUPStatementWrapper> os_statement = [originalEntity getCreateStatement:connection forTable:OriginalStateEntityTable];
				[os_statement executeInsert];
				[os_statement close];					
			}
		}
    	self->_pending = isPending;
	}
	@catch (SUPPersistenceException *spe)
    {
        //MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"createPending",[spe message]);
    	@throw spe;
    }
    @finally
    {
		[statement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }    
}

- (void)updatePending:(BOOL)isPending
{
   	id<SUPConnectionWrapper> connection = nil;
   	id<SUPStatementWrapper> statement = nil;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
    	self->_pending = isPending;
		if(!isPending)
    	{
    		self->_replayPending = 0;
    		self->_replayFailure = 0;
    	}
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
    	statement = [self getUpdateStatement:connection forTable:MainEntityTable];
		[statement executeUpdate:YES];
		self->_isNew = NO;
		self->_isDirty = NO;
		self->_isDeleted = NO;
	}
	@catch (SUPPersistenceException *spe)
    {
        //MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"updatePending",[spe message]);
		@throw spe;
    }
    @finally
    {
		[statement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }    	
}

- (SUPAbstractEntity*)originalState
{
    if (!self->_originalStateValid)
    {
        self->_originalState = self.pending ? [RHM_Comercial_LogRecordImpl find:[self id] inTable:OriginalStateEntityTable] : nil;
        if(self->_originalState == nil && !self.isCreated) self->_originalState = self.downloadState;
        //if(self->_originalState != self) [self->_originalState retain];
        self->_originalStateValid = YES;
    }
    return (SUPAbstractEntity*)(self->_originalState);
}

- (SUPAbstractEntity*)downloadState
{
    if (!self->_downloadStateValid)
    {
        if(self.isNew) 
        {
            self->_downloadState = nil;
        }
        else if(self.pending)
        {
            RHM_Comercial_LogRecordImpl *mbo = [RHM_Comercial_LogRecordImpl find:[self id]];
            if(mbo)
                self->_downloadState = mbo->_downloadState;
            else
                self->_downloadState = nil;
        }
        else
        {
            self->_downloadState = nil;
        }
        self->_downloadStateValid = YES;
    }
    return (SUPAbstractEntity*)(self->_downloadState);
}


- (void)updateOriginalState
{
   	id<SUPConnectionWrapper> connection = nil;
	id<SUPStatementWrapper> statement = nil;
	BOOL savePending = self->_pending;
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
    	connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		self->_pending = NO;
			
		RHM_Comercial_LogRecordImpl* os = [RHM_Comercial_LogRecordImpl find:[self id] inTable:OriginalStateEntityTable];
		if(os)
		{
			statement = [self getUpdateStatement:connection forTable:OriginalStateEntityTable];
			[statement executeUpdate:YES];
		} else {
			statement = [self getCreateStatement:connection forTable:OriginalStateEntityTable];
			[statement executeInsert];
		}
		self->_originalStateValid = NO;
	}
	@catch (SUPPersistenceException *spe)
	{
		MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"updateOriginalState",[spe message]);
	}
    @finally
    {
		self->_pending = savePending;
		[statement close];
        [connection releaseToPool];
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }    
    			
}


- (SUPAbstractEntity*)topLevelParent
{
	return self;
}

- (void)update
{
    @try
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] writeLock];
	    if (self.isDirty)
    	{
        	BOOL pending = self.pending;
            if(self.pendingChange == PendingCreate && self.replayPending > 0) // already submitted
                self->_pendingChange = PendingUpdate;
        	else if (self.pendingChange != PendingCreate && self.pendingChange != PendingDelete)
        	{
        	    self->_pendingChange = PendingUpdate;
        	}
        	self->_replayFailure = 0;
        	self->_replayCounter = 0;
        	if (pending)
        	{
        	    [self updatePending:YES];
        	}
        	else
        	{
        	    [self createPending:YES];
        	}
        }
    }
    @catch (NSException* e)
    {
        @throw e;
    }
    @finally
    {
        [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
    }

}




+ (SUPObjectList*)getPendingObjects
{
	return [self getPendingObjects:0 take:-1]; 
}


	

+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take
{
	SUPObjectList* result = [[[SUPObjectList alloc] init] autorelease];
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:243];
	    [sql appendString:@"select x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"d\",x.\"_rc\",x.\"_ds\" from \"rhm_comercial_1_0_logrecordimpl\" x where x.\"_pc\" <> \'N\' and x.\"_rc\" != x.\"_rp\""];
	    if(take != -1)
	        [sql appendFormat:@" limit %i",take];
	    if(skip != 0)
	        [sql appendFormat:@" offset %i",skip];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        RHM_Comercial_LogRecordImpl* entity = [[RHM_Comercial_LogRecordImpl alloc] init];
	        [entity bind:resultSet];
	        [result add:entity];
			[entity release];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"getPendingObjects",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}



+ (SUPObjectList*)getPendingObjects:(unichar)pendingChange
{
	return [self getPendingObjects:pendingChange skip:0 take:-1]; 
}


	

+ (SUPObjectList*)getPendingObjects:(unichar)pendingChange skip:(int32_t)skip take:(int32_t)take
{
	SUPObjectList* result = [[[SUPObjectList alloc] init] autorelease];
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:238];
	    [sql appendString:@"select x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"d\",x.\"_rc\",x.\"_ds\" from \"rhm_comercial_1_0_logrecordimpl\" x where x.\"_pc\" = ? and x.\"_rc\" != x.\"_rp\""];
	    if(take != -1)
	        [sql appendFormat:@" limit %i",take];
	    if(skip != 0)
	        [sql appendFormat:@" offset %i",skip];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    [preparedStatement setChar:1:@"pendingChange":pendingChange];
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        RHM_Comercial_LogRecordImpl* entity = [[RHM_Comercial_LogRecordImpl alloc] init];
	        [entity bind:resultSet];
	        [result add:entity];
			[entity release];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"getPendingObjects",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}



+ (SUPObjectList*)getReplayPendingObjects
{
	return [self getReplayPendingObjects:0 take:-1]; 
}


	

+ (SUPObjectList*)getReplayPendingObjects:(int32_t)skip take:(int32_t)take
{
	SUPObjectList* result = [[[SUPObjectList alloc] init] autorelease];
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:358];
	    [sql appendString:@"select x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"_pf\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"d\",x.\"_rc\",x.\"_ds\" from \"rhm_comercial_1_0_logrecordimpl\" x where (((x.\"_pf\" = 1 or not exists (select x_os.\"d\" from \"rhm_comercial_1_0_logrecordimpl_os\" x_os where x_os.\"d\" "
	                            "= x.\"d\")))) and ( x.\"_rp\" != 0)"];
	    if(take != -1)
	        [sql appendFormat:@" limit %i",take];
	    if(skip != 0)
	        [sql appendFormat:@" offset %i",skip];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        RHM_Comercial_LogRecordImpl* entity = [[RHM_Comercial_LogRecordImpl alloc] init];
	        [entity bind:resultSet];
	        [result add:entity];
			[entity release];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"getReplayPendingObjects",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}

/*!
  @method
  @abstract Generated class method 
  @param query
  @throws SUPPersistenceException
 */
+ (int32_t)getSize:(SUPQuery*)query
{
    return [RHM_Comercial_LogRecordImpl countWithQuery:query];
}



+ (int32_t)countReplayPendingObjects
{
	int32_t result;
	NSMutableString *sql = nil;
	id<SUPStatementWrapper> preparedStatement = nil;
	id<SUPConnectionWrapper> connection = nil;
	id<SUPResultSetWrapper> resultSet = nil;
	
	@try
	{
	    [[RHM_Comercial_RHM_ComercialDB dblock] readLock];
		connection = [RHM_Comercial_RHM_ComercialDB getConnectionWrapper];
		sql = [[NSMutableString alloc] initWithCapacity:227];
	    [sql appendString:@"select count(*) ,x.\"d\" from \"rhm_comercial_1_0_logrecordimpl\" x where (((x.\"_pf\" = 1 or not exists (select x_os.\"d\" from \"rhm_comercial_1_0_logrecordimpl_os\" x_os where x_os.\"d\" = x.\"d\")))) and ( x.\"_rp\" != 0)"];
	
		preparedStatement = [connection prepareStatement:sql];
	            
	    resultSet = [preparedStatement executeQuery];
	    while ([resultSet next])
	    {
	        result = [resultSet getInt:1:@""];
	    }
	}
	@catch (SUPPersistenceException *spe)
	{
	    MBOLogPersistenceException(SUPCLIENTRT_TEMPLATE_PERSISTENCEEXCEPTIONMSG,@"countReplayPendingObjects",[spe message]);
	}
	@finally
	{
		[sql release];
		if(resultSet) [resultSet close];
		if(preparedStatement) [preparedStatement close];
	    [connection releaseToPool];
	    [[RHM_Comercial_RHM_ComercialDB dblock] unlock];
	}
	return result;
}

@end