/*!
 @discussion Generated by Sybase Unwired Platform, compiler version 2.0.1.314
*/ 



#define CLIENT_DATABASE_CREATED_LOGRECORD_CODE 9999
#define CLIENT_ENTITY_CREATED_LOGRECORD_CODE   9998

#ifdef __DEBUG__

// Define this to have an SUPLogRecord written for each import (useful for testing logging)
#undef LOGRECORD_ON_IMPORT

// Define this to have DB exception messages printed to the console
#define PRINT_PERSISTENCE_MESSAGES

// Define this to print out message headers (and content for replay requests) to the console
#define PRINT_SERVER_MESSAGES

// If PRINT_SERVER_MESSAGES defined, this will also print content for messages coming down from the server
#undef PRINT_SERVER_MESSAGE_CONTENT

#endif //DEBUG