#import "sybase_sup.h"
#import "SUPAnnotations.h"

#import "SUPAbstractEntity.h"
#import "SUPObjectList.h"
#import "SUPLogRecord.h"
#import "SUPLocalBusinessObject.h"
#import "RHM_Comercial_RHM_ComercialDB.h"
#import "RHM_Comercial_SynchronizationGroup.h"


@class SUPEntityMetaData;
@class RHM_Comercial_PersonalizationParameters;

// public interface declaration, can be used by application. 
/*!
 @class RHM_Comercial_ClientesSynchronizationParameters
 @abstract This class is part of package "RHM_Comercial:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.0.1.314
*/ 
@interface RHM_Comercial_ClientesSynchronizationParameters : SUPAbstractEntity<SUPLocalBusinessObject>
{
@private
    NSString* _agente;
    BOOL _agenteUserDefined;
    int32_t _size;
    NSString* _user;
}

@property(retain,nonatomic) NSString* agente;
@property(assign,nonatomic) BOOL agenteUserDefined;
@property(assign,nonatomic) int32_t size;
@property(retain,nonatomic) NSString* user;

- (void)dealloc;
/*!
  @method 
  @abstract Sets relationship attributes to null to save memory (they will be retrieved from the DB on the next getter call or property reference)
  @discussion
  @throws SUPPersistenceException
 */
- (void)clearRelationshipObjects;
- (void)createOrUpdateClientOnly;
/*!
  @method 
  @abstract Copy all attributes (except relationships) from 'other' to this entity
  @discussion
 */
- (void)copyAll:(RHM_Comercial_ClientesSynchronizationParameters*)other;
/*!
  @method 
  @abstract Returns the entity for the primary key value passed in, or null if the entity is not found.
  @discussion
  @throws SUPPersistenceException
 */
+ (RHM_Comercial_ClientesSynchronizationParameters*)find:(NSString*)id;
/*!
  @method 
  @abstract Same as the find method above, but takes a string representation of the primary key as its parameter.
  @discussion
  @throws SUPPersistenceException
 */
+ (RHM_Comercial_ClientesSynchronizationParameters*)find_by_id_string:(NSString*)id_string;
/*!
  @method 
  @abstract Return the synchronization group for this MBO class
  @discussion
 */
+ (id<SUPSynchronizationGroup>)getSynchronizationGroup;
/*!
  @method 
  @abstract Returns the primary key for this entity.
  @discussion
 */
- (NSString*)_pk;
- (NSString*)id;
/*!
  @method 
  @abstract Returns the primary key for this entity as a string.
  @discussion
 */
- (NSString*)keyToString;
/*!
  @method 
  @abstract Returns the entity for the primary key value passed in; throws an exception if the entity is not found.
  @discussion
  @throws SUPPersistenceException
 */
+ (RHM_Comercial_ClientesSynchronizationParameters*)load:(NSString*)id;
+ (SUPEntityMetaData*)metaData;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (RHM_Comercial_ClientesSynchronizationParameters*)getInstance;
/*!
  @method 
  @abstract Returns an SUPObjectList of log records for this entity.
  @discussion
  @throws SUPPersistenceException
 */
- (SUPObjectList*)getLogRecords;
/*!
  @method 
  @abstract Creates a new log record for this entity.
  @discussion
  @throws SUPPersistenceException
 */
- (id<SUPLogRecord>)createLogRecord:(int32_t)level withMessage:(NSString*)message;
/*!
  @method 
  @abstract Saves (creates or updates) this entity in the database.
  @discussion
  @throws SUPPersistenceException
 */
- (void)save;
/*!
  @method 
  @abstract Return a string description of this entity.
  @discussion
 */
- (NSString*)toString;
/*!
  @method 
  @abstract Return a string description of this entity.
  @discussion
 */
- (NSString*)description;


@end

typedef SUPObjectList RHM_Comercial_ClientesSynchronizationParametersList;

// internal methods declaration, only used by generated code.
@interface RHM_Comercial_ClientesSynchronizationParameters(internal)


- (id)initFromJson:(SUPJsonObject*)json:(int32_t)flags;
- (void)readJson:(SUPJsonObject*)json:(int32_t)flags;
- (SUPJsonObject*)json:(int32_t)flags;
+ (SUPObjectList*)fromJSONList:(SUPJsonArray*)jsonArray NS_RETURNS_RETAINED;
+ (SUPJsonArray*)toJSONList:(SUPObjectList*)instanceList;


- (RHM_Comercial_RHM_ComercialDB*)database;
/*!
  @method
  @abstract Generated instance method 
  @throws SUPPersistenceException
 */
- (void)beforeSave;
/*!
  @method
  @abstract Generated instance method 
  @param pp
  @throws SUPPersistenceException
 */
- (void)beforeSync:(RHM_Comercial_PersonalizationParameters*)pp;
/*!
  @method
  @abstract Generated instance method 
  @param pp
  @throws SUPPersistenceException
 */
- (NSString*)getAgenteForSub0:(RHM_Comercial_PersonalizationParameters*)pp;
- (SUPAbstractEntity*)topLevelParent;
@end