#import "sybase_sup.h"
#import "SUPAnnotations.h"


#import "SUPClassMetaData.h"
#import "RHM_Comercial_RHM_ComercialDB.h"
#import "SUPJsonObject.h"
#import "SUPJsonArray.h"
#import "RHM_Comercial_LogRecordImpl.h"


@class SUPLogRecord;

// public interface declaration, can be used by application. 
/*!
 @class RHM_Comercial_LocalKeyGeneratorPK
 @abstract This class is part of package "RHM_Comercial:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.0.1.314
*/ 
@interface RHM_Comercial_LocalKeyGeneratorPK : NSObject
{
@private
    NSString* _remoteId;
    int64_t _batchId;
}

@property(retain,nonatomic) NSString* remoteId;
@property(assign,nonatomic) int64_t batchId;

- (void)dealloc;
+ (SUPClassMetaData*)metaData;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (RHM_Comercial_LocalKeyGeneratorPK*)getInstance;


@end

typedef SUPObjectList RHM_Comercial_LocalKeyGeneratorPKList;

// internal methods declaration, only used by generated code.
@interface RHM_Comercial_LocalKeyGeneratorPK(internal)


- (id)initFromJson:(SUPJsonObject*)json:(int32_t)flags;
- (void)readJson:(SUPJsonObject*)json:(int32_t)flags;
- (SUPJsonObject*)json:(int32_t)flags;
+ (SUPObjectList*)fromJSONList:(SUPJsonArray*)jsonArray NS_RETURNS_RETAINED;
+ (SUPJsonArray*)toJSONList:(SUPObjectList*)instanceList;



@end