#import "sybase_sup.h"
#import "SUPAnnotations.h"


#import "SUPClassMetaData.h"
#import "RHM_Comercial_RHM_ComercialDB.h"
#import "SUPJsonObject.h"
#import "SUPJsonArray.h"
#import "RHM_Comercial_LogRecordImpl.h"


@class SUPObjectList;
@class SUPLogRecord;

// public interface declaration, can be used by application. 
/*!
 @class RHM_Comercial_PersonalizationParameters
 @abstract This class is part of package "RHM_Comercial:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.0.1.314
*/ 
@interface RHM_Comercial_PersonalizationParameters : NSObject
{
@private
    SUPObjectList* _listSessionPK;
    NSString* _username;
    BOOL _usernameUserDefined;
    NSString* _password;
    BOOL _passwordUserDefined;
}

@property(retain,nonatomic) SUPObjectList* listSessionPK;
@property(retain,nonatomic) NSString* username;
@property(assign,nonatomic) BOOL usernameUserDefined;
@property(retain,nonatomic) NSString* password;
@property(assign,nonatomic) BOOL passwordUserDefined;

- (void)dealloc;
+ (SUPClassMetaData*)metaData;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (RHM_Comercial_PersonalizationParameters*)getInstance;
/*!
  @method
  @abstract Generated instance method 
  @throws SUPPersistenceException
 */
- (void)load;
/*!
  @method
  @abstract Generated instance method 
  @throws SUPPersistenceException
 */
- (void)save;
/*!
  @method
  @abstract Generated instance method 
  @throws SUPPersistenceException
 */
- (void)saveUserNamePassword;


@end

typedef SUPObjectList RHM_Comercial_PersonalizationParametersList;

// internal methods declaration, only used by generated code.
@interface RHM_Comercial_PersonalizationParameters(internal)


- (id)initFromJson:(SUPJsonObject*)json:(int32_t)flags;
- (void)readJson:(SUPJsonObject*)json:(int32_t)flags;
- (SUPJsonObject*)json:(int32_t)flags;
+ (SUPObjectList*)fromJSONList:(SUPJsonArray*)jsonArray NS_RETURNS_RETAINED;
+ (SUPJsonArray*)toJSONList:(SUPObjectList*)instanceList;



@end